USE roadmap;
CREATE TABLE IF NOT EXISTS plan_days (
  day_no INT PRIMARY KEY,
  week_no INT NOT NULL,
  stage TINYINT NOT NULL,
  theme VARCHAR(200) NOT NULL,
  output VARCHAR(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS todos (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  day_no INT NOT NULL,
  slot VARCHAR(10) NOT NULL,
  slot_name VARCHAR(20) NOT NULL,
  content VARCHAR(500) NOT NULL,
  done TINYINT DEFAULT 0,
  done_at DATETIME NULL,
  KEY idx_day (day_no),
  CONSTRAINT fk_todos_day FOREIGN KEY (day_no) REFERENCES plan_days(day_no) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
