INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 1, 1, 1, '定位与人群', '确定账号方向');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 1, 'am', '学习', '研究小红书/视频号算法基础，理解''标签-人群-内容''匹配', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 1, 'pm', '实战', '确定账号定位：结合前端+AI+独立开发，写一份定位文档（我是谁/给谁/解决什么）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 1, 'ev', '复盘', '找 5 个对标账号，记录他们的定位和爆款特征', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 1, 'extra', '表达', '录 60 秒自我介绍：我是谁我能给粉丝什么（练定位表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 2, 1, 1, '账号注册与装修', '主页让人一眼懂你');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 2, 'am', '学习', '学习主页装修要素：昵称/简介/头像/背景/置顶', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 2, 'pm', '实战', '注册/优化账号，写一句能记住的简介，设计统一视觉', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 2, 'ev', '复盘', '记录主页装修 checklist', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 2, 'extra', '表达', '对着手机念 3 遍简介，录最自然的一版（练一句话表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 3, 1, 1, '选题库搭建', '有源源不断的内容');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 3, 'am', '学习', '学习选题方法：痛点/教程/盘点/对比/故事', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 3, 'pm', '实战', '用表格建选题库，列 30 个选题（结合 AI+前端+独立开发）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 3, 'ev', '复盘', '按''我能写+有人看+有差异''给选题打分排序', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 3, 'extra', '表达', '口述：我最想写的 3 个选题及理由，录音（练选题表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 4, 1, 1, '图文写作基础', '写出能读完的第一篇');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 4, 'am', '学习', '学习小红书图文结构：标题钩子+开头+正文+结尾互动', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 4, 'pm', '实战', '写第一篇图文（教程类），控制在 500 字内', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 4, 'ev', '复盘', '记录写作模板和自己的易错点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 4, 'extra', '表达', '大声朗读第一篇图文 3 遍，录音听流畅度（练书面转口语）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 5, 1, 1, '标题与封面', '前 3 秒决定生死');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 5, 'am', '学习', '学习标题公式（数字/痛点/反差/好奇）和封面设计原则', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 5, 'pm', '实战', '给第一篇配 3 版标题+3 版封面，对比选最优', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 5, 'ev', '复盘', '整理标题模板库 20 条', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 5, 'extra', '表达', '口述：好标题的 3 个共性，录音≤45 秒', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 6, 1, 1, '发布与数据', '发出第一篇并看数据');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 6, 'am', '学习', '学习发布时机/标签/位置/@ 等发布技巧', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 6, 'pm', '实战', '发布第一篇，2 小时后记录数据（阅读/点赞/评论）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 6, 'ev', '复盘', '分析数据：哪里好哪里差，写改进点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 6, 'extra', '表达', '对着手机讲：第一篇的复盘，录音（练数据复盘表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 7, 1, 1, '周复盘', '第一周内容基建完成');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 7, 'am', '学习', '回顾本周定位/选题/写作，查漏补缺', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 7, 'pm', '实战', '整理本周所有素材到素材库', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 7, 'ev', '复盘', '写周记：第一周的惊喜和困难', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 7, 'extra', '表达', '录 2 分钟周复盘，刻意练''有重点地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 8, 2, 1, '表达基础：敢开口', '克服内向开口难');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 8, 'am', '学习', '学习内向者表达心法：准备充分/小步暴露/接受不完美', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 8, 'pm', '实战', '每天对手机录 3 条 30 秒语音讲一个观点，连做记录', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 8, 'ev', '复盘', '整理''我开口最怕什么''清单，逐条找对策', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 8, 'extra', '表达', '录 1 分钟：我为什么想做自媒体，连录 5 遍取最好的（练敢开口）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 9, 2, 1, '表达基础：有逻辑', '说话不散');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 9, 'am', '学习', '学习表达结构：总分总/STAR/过去现在未来/问题方案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 9, 'pm', '实战', '用''总分总''结构录 3 条 1 分钟语音（讲一个技术点）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 9, 'ev', '复盘', '回听录音，标记逻辑断裂处', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 9, 'extra', '表达', '对着镜子讲：什么是 RAG，用总分总结构，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 10, 2, 1, '表达基础：有重点', '让人记得住');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 10, 'am', '学习', '学习''一句话说清''训练：每个内容先写一句核心句', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 10, 'pm', '实战', '把 5 个选题各浓缩成一句话核心句', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 10, 'ev', '复盘', '记录''我说太长''的毛病及修正', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 10, 'extra', '表达', '口述：我的账号一句话介绍，录音≤20 秒（练极简表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 11, 2, 1, '短视频脚本', '图文转视频的第一步');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 11, 'am', '学习', '学习短视频脚本结构：钩子(3s)+痛点+方案+行动', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 11, 'pm', '实战', '把一篇图文改写成 60 秒短视频脚本', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 11, 'ev', '复盘', '整理脚本模板', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 11, 'extra', '表达', '朗读脚本 5 遍录音，练到不卡壳（练脚本口语化）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 12, 2, 1, '录屏实操', '不出镜也能做视频');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 12, 'am', '学习', '学习录屏工具（剪映/OBS），规划画面分镜', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 12, 'pm', '实战', '录一条录屏+配音的短视频（不出镜），剪辑成片', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 12, 'ev', '复盘', '记录录屏视频的 5 个制作要点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 12, 'extra', '表达', '发动态：我的第一条短视频（练成果公开表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 13, 2, 1, '配音与节奏', '声音也是表达力');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 13, 'am', '学习', '学习配音技巧：语速/停顿/重音/情绪', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 13, 'pm', '实战', '给视频重新配音 3 版，对比哪个最自然', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 13, 'ev', '复盘', '整理配音 checklist', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 13, 'extra', '表达', '口述：我发现我说话的毛病是___，录音（练自我觉察表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 14, 2, 1, '周复盘', '第二周表达突破');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 14, 'am', '学习', '回顾本周表达训练，对比第 1 天和今天的录音', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 14, 'pm', '实战', '整理本周短视频脚本和成片', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 14, 'ev', '复盘', '写周记：表达练习带来的变化', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 14, 'extra', '表达', '录 2 分钟：两周来我的表达进步，练''有对比地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 15, 3, 1, '内容支柱设计', '3 条腿站稳');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 15, 'am', '学习', '学习内容支柱法：选 3 个固定主题轮转', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 15, 'pm', '实战', '确定 3 个支柱（如：AI 工具教程/独立开发日记/前端转行经验）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 15, 'ev', '复盘', '给每个支柱列 10 个选题', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 15, 'extra', '表达', '口述：我的 3 个内容支柱为什么这么选，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 16, 3, 1, '小红书爆款拆解', '向爆款学结构');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 16, 'am', '学习', '找 5 篇同领域爆款，拆解标题/封面/开头/结构', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 16, 'pm', '实战', '整理爆款共性清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 16, 'ev', '复盘', '用爆款结构改写自己的一篇旧文', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 16, 'extra', '表达', '对着手机讲：爆款为什么爆，录音≤1 分钟', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 17, 3, 1, '视频号入门', '理解视频号生态');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 17, 'am', '学习', '学习视频号算法（社交推荐+算法推荐），对比小红书', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 17, 'pm', '实战', '把已发的短视频同步到视频号，观察数据差异', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 17, 'ev', '复盘', '记录两个平台的受众差异', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 17, 'extra', '表达', '口述：小红书和视频号的区别，录音（练对比表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 18, 3, 1, '系列内容规划', '让用户追更');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 18, 'am', '学习', '学习系列内容的价值：培养期待/提升复访', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 18, 'pm', '实战', '规划一个 5 期的系列（如''AI 工具每天一个''）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 18, 'ev', '复盘', '写系列大纲', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 18, 'extra', '表达', '录 1 分钟：我为什么做这个系列，练''预告式表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 19, 3, 1, '互动与评论区', '评论也是内容');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 19, 'am', '学习', '学习评论运营：回复/置顶/引发讨论', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 19, 'pm', '实战', '给所有已发内容的评论做回复，设计互动话术', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 19, 'ev', '复盘', '记录高互动评论的特征', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 19, 'extra', '表达', '口述：怎么让评论区热闹起来，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 20, 3, 1, '数据复盘', '用数据指导内容');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 20, 'am', '学习', '学习核心指标：曝光/点击率/完播/互动率', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 20, 'pm', '实战', '导出本月数据，找出最佳/最差内容，分析原因', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 20, 'ev', '复盘', '制定下月内容优化方向', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 20, 'extra', '表达', '对着手机讲：我的数据告诉我什么，录音（练数据表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 21, 3, 1, '周复盘', '第三周体系化');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 21, 'am', '学习', '回顾本周支柱/系列/数据，整理方法论', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 21, 'pm', '实战', '把内容方法论写成一篇''我的自媒体心法''存草稿', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 21, 'ev', '复盘', '写周记：从单篇到体系的转变', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 21, 'extra', '表达', '录 2 分钟：我的内容方法论，练''有体系地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 22, 4, 1, '差异化定位', '找到只有你能写的角度');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 22, 'am', '学习', '学习差异化方法：你的经历就是壁垒（前端+AI+ISTP+内向）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 22, 'pm', '实战', '写下只有你能写的内容角度 5 条', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 22, 'ev', '复盘', '选定 1 个差异化方向深耕', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 22, 'extra', '表达', '口述：我和别人不一样在哪，录音（练差异化表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 23, 4, 1, '个人故事内容', '故事比知识更传播');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 23, 'am', '学习', '学习故事化表达：困境-转折-行动-结果', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 23, 'pm', '实战', '写一篇''内向前端工程师为什么做自媒体''的故事图文', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 23, 'ev', '复盘', '记录故事化写作要点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 23, 'extra', '表达', '对着镜子讲自己的故事 2 分钟，录音（练故事表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 24, 4, 1, '视觉统一', '一眼认出是你');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 24, 'am', '学习', '学习视觉规范：配色/字体/封面模板', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 24, 'pm', '实战', '做一套统一封面模板（Canva/PS），套用到所有图文', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 24, 'ev', '复盘', '整理视觉规范文档', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 24, 'extra', '表达', '发动态：我的账号换新装了（练视觉成果表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 25, 4, 1, '跨平台分发', '一鱼多吃');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 25, 'am', '学习', '学习跨平台分发策略：内容改造而非照搬', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 25, 'pm', '实战', '把一篇内容改造成小红书/视频号/知乎 3 个版本发布', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 25, 'ev', '复盘', '记录各平台改造要点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 25, 'extra', '表达', '口述：同一内容怎么适配不同平台，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 26, 4, 1, '表达进阶：讲故事', '让技术内容有温度');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 26, 'am', '学习', '学习技术内容故事化：用''我踩的坑''替代''你应该''', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 26, 'pm', '实战', '把一篇教程改写成''我踩坑的故事''版本', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 26, 'ev', '复盘', '对比两种版本的可读性', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 26, 'extra', '表达', '录 90 秒：讲一个我技术踩坑的故事，练''有画面感地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 27, 4, 1, '表达进阶：会提问', '提问比回答更吸引');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 27, 'am', '学习', '学习提问式表达：用问题引发共鸣和互动', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 27, 'pm', '实战', '写一篇以提问开头的图文，测试互动率', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 27, 'ev', '复盘', '整理提问模板库', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 27, 'extra', '表达', '口述：好问题长什么样，录音≤45 秒', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 28, 4, 1, '出镜初尝试', '从录屏到出镜的过渡');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 28, 'am', '学习', '学习出镜前的准备：脚本/光线/机位/状态', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 28, 'pm', '实战', '录一条''手部出镜+配音''的视频（不全脸出镜），降低心理门槛', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 28, 'ev', '复盘', '记录出镜的心理感受和改进点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 28, 'extra', '表达', '对着镜头说 30 秒自我介绍，录音看表情（练镜头前表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 29, 4, 1, '阶段一收尾', '内容基建完成');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 29, 'am', '学习', '对照阶段一目标检查：定位/选题/表达/视觉是否到位', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 29, 'pm', '实战', '整理阶段一所有内容资产', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 29, 'ev', '复盘', '写阶段一总结：我学到的最重要的 3 件事', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 29, 'extra', '表达', '录 3 分钟：我的阶段一复盘，练''有深度地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 30, 4, 1, '缓冲日', '追赶进度');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 30, 'am', '学习', '补完落后内容，或深化某个方向', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 30, 'pm', '实战', '整理素材库和选题库', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 30, 'ev', '复盘', '写月度复盘发到知识星球/备忘录', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 30, 'extra', '表达', '录 2 分钟：这 30 天我最骄傲的一篇内容，练''有热情地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 31, 5, 2, '爆款选题法', '主动制造爆款');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 31, 'am', '学习', '学习爆款选题公式：争议/反差/时效/情绪', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 31, 'pm', '实战', '用公式生成 10 个爆款候选选题，选 1 个写', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 31, 'ev', '复盘', '记录爆款选题的判断标准', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 31, 'extra', '表达', '口述：我觉得会爆的选题及理由，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 32, 5, 2, '情绪共鸣', '让内容被转发');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 32, 'am', '学习', '学习情绪营销：共鸣/焦虑/治愈/爽感', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 32, 'pm', '实战', '给一篇内容加情绪锚点，测试转发率', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 32, 'ev', '复盘', '整理''情绪-选题''对照表', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 32, 'extra', '表达', '对着手机讲：什么内容会让人想转发，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 33, 5, 2, '蹭热点', '借势不跟风');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 33, 'am', '学习', '学习蹭热点的边界和方法（AI 领域热点）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 33, 'pm', '实战', '结合一个当下 AI 热点，快速出一篇内容', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 33, 'ev', '复盘', '记录蹭热点的时效窗口', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 33, 'extra', '表达', '口述：我怎么判断要不要蹭这个热点，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 34, 5, 2, '评论区运营', '把流量变留量');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 34, 'am', '学习', '学习评论区引流和社群转化', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 34, 'pm', '实战', '在评论区设计''钩子''引导关注，建一个轻量粉丝群', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 34, 'ev', '复盘', '记录评论转化的数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 34, 'extra', '表达', '录 1 分钟：欢迎新粉丝的话术，练''有亲和力地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 35, 5, 2, '涨粉活动', '设计增长动作');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 35, 'am', '学习', '学习涨粉活动设计：抽奖/挑战/合集', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 35, 'pm', '实战', '做一个''关注+评论抽 AI 工具包''的小活动', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 35, 'ev', '复盘', '记录活动数据和成本', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 35, 'extra', '表达', '对着镜头讲活动规则 60 秒，练''清晰传达表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 36, 5, 2, '视频号直播初探', '直播是表达加速器');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 36, 'am', '学习', '学习视频号直播基础（内向者从语音直播起步）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 36, 'pm', '实战', '开一场 15 分钟语音直播（不露脸），讲一个技术点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 36, 'ev', '复盘', '记录直播感受和数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 36, 'extra', '表达', '口述：第一次直播我紧张在哪，录音（练真实感受表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 37, 5, 2, '周复盘', '第二阶段开门红');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 37, 'am', '学习', '回顾本周破圈动作，分析效果', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 37, 'pm', '实战', '整理本周爆款/热点内容', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 37, 'ev', '复盘', '写周记：从内容到流量的跃迁', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 37, 'extra', '表达', '录 2 分钟：破圈这周我做对了什么，练''有自信地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 38, 6, 2, '粉丝画像', '懂粉丝才能留存');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 38, 'am', '学习', '学习粉丝画像分析：年龄/职业/需求/痛点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 38, 'pm', '实战', '用问卷/评论区/私信整理粉丝画像', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 38, 'ev', '复盘', '根据画像调整内容方向', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 38, 'extra', '表达', '口述：我的粉丝是谁，他们要什么，录音（练用户洞察表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 39, 6, 2, '内容矩阵', '主号+垂类号');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 39, 'am', '学习', '学习内容矩阵策略：主号带信任，垂类号带流量', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 39, 'pm', '实战', '评估是否开第二个垂类号（如纯 AI 工具号）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 39, 'ev', '复盘', '记录矩阵运营的成本评估', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 39, 'extra', '表达', '对着镜子讲：我要不要做矩阵，理由是___，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 40, 6, 2, 'SEO 与长尾', '让内容持续被搜到');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 40, 'am', '学习', '学习小红书/视频号的搜索流量逻辑', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 40, 'pm', '实战', '给旧内容优化关键词，观察搜索流量变化', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 40, 'ev', '复盘', '整理 SEO 关键词库', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 40, 'extra', '表达', '口述：搜索流量和推荐流量的区别，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 41, 6, 2, '合作与互推', '借力打力');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 41, 'am', '学习', '学习同量级账号合作方法', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 41, 'pm', '实战', '找 2 个同领域账号谈互推/合作内容', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 41, 'ev', '复盘', '记录合作的话术和结果', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 41, 'extra', '表达', '对着手机讲：我怎么开口找人合作，录音（练商务表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 42, 6, 2, '出镜突破', ' ISTP 的镜头挑战');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 42, 'am', '学习', '学习出镜心法：准备到位/允许不完美/小步迭代', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 42, 'pm', '实战', '录第一条全脸出镜短视频（60 秒），发出', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 42, 'ev', '复盘', '记录出镜前后的心理变化', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 42, 'extra', '表达', '录 2 分钟：我为什么终于敢出镜，练''有勇气地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 43, 6, 2, '直播进阶', '从语音到露脸');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 43, 'am', '学习', '学习露脸直播的设备和状态管理', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 43, 'pm', '实战', '开一场 30 分钟露脸直播，主题分享', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 43, 'ev', '复盘', '记录直播数据和观众反馈', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 43, 'extra', '表达', '口述：露脸直播和语音直播的区别，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 44, 6, 2, '周复盘', '流量持续增长');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 44, 'am', '学习', '回顾本周粉丝增长数据，找增长杠杆', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 44, 'pm', '实战', '整理本周增长实验清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 44, 'ev', '复盘', '写周记：增长背后的逻辑', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 44, 'extra', '表达', '录 2 分钟：我这周涨粉的原因分析，练''有逻辑地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 45, 7, 2, '个人 IP 故事', '让粉丝记住''你这个人''');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 45, 'am', '学习', '学习个人 IP 故事化：标签/经历/价值观', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 45, 'pm', '实战', '写一篇''我是谁''的品牌故事图文/视频', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 45, 'ev', '复盘', '记录个人 IP 的 3 个关键词', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 45, 'extra', '表达', '对着镜头讲：用 3 个词形容我自己，练''有标签地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 46, 7, 2, '危机与口碑', '应对负面');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 46, 'am', '学习', '学习应对差评/质疑/搬运', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 46, 'pm', '实战', '制定负面应对话术和流程', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 46, 'ev', '复盘', '记录''被质疑时''的表达原则', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 46, 'extra', '表达', '口述：被杠精攻击我怎么回，录音（练冷静表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 47, 7, 2, '私域沉淀', '把粉丝变资产');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 47, 'am', '学习', '学习私域运营：粉丝群/朋友圈/知识星球', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 47, 'pm', '实战', '建一个粉丝群或加微信，设计入群话术', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 47, 'ev', '复盘', '记录私域转化率', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 47, 'extra', '表达', '对着手机讲：欢迎进群的话术，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 48, 7, 2, '粉丝活动', '提升粘性');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 48, 'am', '学习', '学习粉丝活动设计：答疑/打卡/直播', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 48, 'pm', '实战', '做一次''粉丝问答直播''或''7 天打卡''活动', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 48, 'ev', '复盘', '记录活动参与率和满意度', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 48, 'extra', '表达', '口述：我怎么设计让粉丝愿意参与的活动，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 49, 7, 2, '内容升级', '从量到质');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 49, 'am', '学习', '学习内容升级：深度长文/精品视频/系列课', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 49, 'pm', '实战', '把一个爆款选题升级为深度长文或精品视频', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 49, 'ev', '复盘', '记录精品内容的生产成本', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 49, 'extra', '表达', '对着镜子讲：我要做精品内容还是高频内容，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 50, 7, 2, '数据复盘', '阶段二中段检查');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 50, 'am', '学习', '分析近 20 天数据，找趋势', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 50, 'pm', '实战', '调整内容策略', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 50, 'ev', '复盘', '写阶段二中段复盘', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 50, 'extra', '表达', '录 2 分钟：我的内容策略调整，练''有数据支撑地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 51, 7, 2, '周复盘', '破圈阶段完成');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 51, 'am', '学习', '回顾阶段二，确认流量破圈目标达成度', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 51, 'pm', '实战', '整理破圈方法论', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 51, 'ev', '复盘', '写周记：从 0 到 1000 粉的心路', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 51, 'extra', '表达', '录 3 分钟：我的破圈经验，练''有方法论地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 52, 8, 2, '数据深度分析', '找增长杠杆');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 52, 'am', '学习', '学习内容数据深度分析：漏斗/人群/时段/选题', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 52, 'pm', '实战', '导出近 50 天数据，找出增长最快的选题类型和时段', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 52, 'ev', '复盘', '记录增长杠杆清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 52, 'extra', '表达', '对着手机讲：数据告诉我接下来怎么做，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 53, 8, 2, '内容矩阵落地', '主号带号矩阵');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 53, 'am', '学习', '学习内容矩阵落地：主号定信任，副号带流量', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 53, 'pm', '实战', '启动一个垂直副号（如纯 AI 工具号），发 3 篇试水', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 53, 'ev', '复盘', '记录矩阵运营成本和初步数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 53, 'extra', '表达', '口述：我的矩阵怎么分工，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 54, 8, 2, '直播常规化', '把直播变习惯');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 54, 'am', '学习', '学习直播常规化：固定时间/主题/复盘', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 54, 'pm', '实战', '固定每周 1 场直播，连开 2 场并复盘', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 54, 'ev', '复盘', '记录直播数据趋势', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 54, 'extra', '表达', '对着镜头讲：我的直播怎么排，录音（练镜头表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 55, 8, 2, '跨平台分发优化', '一鱼多吃升级');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 55, 'am', '学习', '学习跨平台分发优化：各平台改造重点和数据回流', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 55, 'pm', '实战', '把 1 篇爆款改造成 4 平台版本，对比各平台数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 55, 'ev', '复盘', '记录跨平台分发 SOP', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 55, 'extra', '表达', '口述：同一内容各平台怎么改，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 56, 8, 2, '粉丝活动 2', '提升粘性与裂变');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 56, 'am', '学习', '学习粉丝裂变活动：邀请/打卡/UGC', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 56, 'pm', '实战', '做一个''带 1 个朋友进群''或''7 天打卡''裂变活动', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 56, 'ev', '复盘', '记录裂变数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 56, 'extra', '表达', '对着手机讲：我的裂变活动怎么设计，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 57, 8, 2, '口碑管理', '守住好评');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 57, 'am', '学习', '学习口碑管理：好评引导/差评应对/搬运维权', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 57, 'pm', '实战', '制定口碑管理 SOP，处理一批历史差评', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 57, 'ev', '复盘', '记录口碑风险点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 57, 'extra', '表达', '口述：怎么让粉丝自发说好话，录音（练口碑表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 58, 8, 2, '周复盘', '破圈深化完成');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 58, 'am', '学习', '回顾本周深化动作，盘点增长', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 58, 'pm', '实战', '整理阶段二全部增长实验', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 58, 'ev', '复盘', '写周记：从破圈到深耕', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 58, 'extra', '表达', '录 2 分钟：我的增长方法论，练''有体系地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 59, 8, 2, '阶段二总复盘', '破圈阶段收尾');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 59, 'am', '学习', '对照阶段二目标逐项检查', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 59, 'pm', '实战', '整理阶段二内容/粉丝/数据资产', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 59, 'ev', '复盘', '写阶段二总结', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 59, 'extra', '表达', '对着镜子讲：阶段二我最大的突破，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 60, 8, 2, '缓冲日', '阶段切换休整');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 60, 'am', '学习', '补完落后内容，休整', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 60, 'pm', '实战', '准备阶段三变现物料', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 60, 'ev', '复盘', '写阶段切换备忘', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 60, 'extra', '表达', '录 2 分钟：准备进入变现，练''有期待地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 61, 9, 3, '变现路径盘点', '知道钱在哪');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 61, 'am', '学习', '学习自媒体变现模式：广告/带货/付费内容/咨询/社群', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 61, 'pm', '实战', '结合自身定位，列出 5 条可行变现路径', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 61, 'ev', '复盘', '按''可行+匹配+收益''排序', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 61, 'extra', '表达', '口述：我的变现路径排序及理由，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 62, 9, 3, '广告接单准备', '让品牌找得到你');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 62, 'am', '学习', '学习接广告流程：报价单/媒介库/合作话术', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 62, 'pm', '实战', '做一份媒体报价单，整理已发内容数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 62, 'ev', '复盘', '记录报价策略', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 62, 'extra', '表达', '对着手机讲：我的账号值多少钱为什么，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 63, 9, 3, '付费内容设计', '把知识变产品');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 63, 'am', '学习', '学习付费内容设计：小册/专栏/训练营', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 63, 'pm', '实战', '规划一个 9.9 元的小册（10 篇），写大纲', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 63, 'ev', '复盘', '记录付费内容的定价逻辑', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 63, 'extra', '表达', '口述：我的小册解决什么问题谁会买，录音（练产品表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 64, 9, 3, '付费内容生产 1', '先把内容做出来');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 64, 'am', '学习', '学习付费内容生产节奏：先完稿再上线', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 64, 'pm', '实战', '写小册前 3 篇初稿', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 64, 'ev', '复盘', '记录付费内容写作心得', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 64, 'extra', '表达', '对着镜子讲：我的小册卖点是什么，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 65, 9, 3, '付费内容生产 2', '补齐内容');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 65, 'am', '学习', '学习内容打磨：案例/配图/可操作性', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 65, 'pm', '实战', '完成小册 10 篇初稿', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 65, 'ev', '复盘', '整理小册目录和卖点文案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 65, 'extra', '表达', '口述：用 1 分钟卖我的小册，练''有说服力地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 66, 9, 3, '轻量社群搭建', '沉淀高价值粉丝');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 66, 'am', '学习', '学习轻量社群运营：知识星球/小报童', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 66, 'pm', '实战', '开通知识星球，写社群介绍和入群福利', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 66, 'ev', '复盘', '记录社群冷启动策略', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 66, 'extra', '表达', '录 1 分钟：为什么我的星球值得加入，练''价值表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 67, 9, 3, '周复盘', '变现准备就绪');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 67, 'am', '学习', '回顾本周变现准备，检查产品就绪度', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 67, 'pm', '实战', '整理变现物料清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 67, 'ev', '复盘', '写周记：从内容到产品的心态转变', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 67, 'extra', '表达', '录 2 分钟：我要开始变现了，练''有底气地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 68, 10, 3, '小册上线', '第一笔知识付费');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 68, 'am', '学习', '学习小册上架流程和预热话术', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 68, 'pm', '实战', '上线小册，发 3 条预热内容（图文+视频+直播）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 68, 'ev', '复盘', '记录首日销售数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 68, 'extra', '表达', '口述：我的小册卖得怎么样为什么，录音（练结果表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 69, 10, 3, '星球冷启动', '把粉丝转化进社群');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 69, 'am', '学习', '学习社群冷启动：种子用户/打卡/答疑', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 69, 'pm', '实战', '邀请前 50 名粉丝进星球，设计打卡活动', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 69, 'ev', '复盘', '记录星球活跃度', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 69, 'extra', '表达', '对着手机讲：星球第一周欢迎话术，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 70, 10, 3, '接第一个广告', '商业化里程碑');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 70, 'am', '学习', '学习广告合作执行：Brief/报价/交付/合规', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 70, 'pm', '实战', '接第一个广告（或主动找 1 个品牌谈），完成交付', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 70, 'ev', '复盘', '记录广告收入和耗时', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 70, 'extra', '表达', '发动态/对粉丝坦诚：我的第一个广告（练''真诚表达'')', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 71, 10, 3, '数据分析变现', '优化变现结构');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 71, 'am', '学习', '分析各变现路径的投入产出比', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 71, 'pm', '实战', '调整精力分配（广告 vs 付费内容 vs 社群）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 71, 'ev', '复盘', '记录变现结构优化方案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 71, 'extra', '表达', '口述：我的变现组合怎么优化，录音（练结构化表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 72, 10, 3, '直播变现', '视频号直播带货/打赏');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 72, 'am', '学习', '学习视频号直播变现：打赏/带货/引流', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 72, 'pm', '实战', '开一场主题直播，测试变现路径', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 72, 'ev', '复盘', '记录直播变现数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 72, 'extra', '表达', '对着镜头讲：直播变现怎么做，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 73, 10, 3, '知识付费迭代', '让产品更好卖');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 73, 'am', '学习', '学习付费产品迭代：根据反馈加值', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 73, 'pm', '实战', '根据小册/星球反馈，更新内容', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 73, 'ev', '复盘', '记录迭代带来的转化变化', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 73, 'extra', '表达', '口述：我怎么根据反馈改产品，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 74, 10, 3, '周复盘', '变现跑通');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 74, 'am', '学习', '回顾本周变现数据，确认模式可行', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 74, 'pm', '实战', '整理变现 SOP', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 74, 'ev', '复盘', '写周记：第一次靠内容赚钱的感受', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 74, 'extra', '表达', '录 2 分钟：自媒体变现的真相，练''有真实感地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 75, 11, 3, '个人品牌升级', '从内容到品牌');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 75, 'am', '学习', '学习个人品牌升级：视觉/故事/产品矩阵', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 75, 'pm', '实战', '更新主页和视觉，规划产品矩阵', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 75, 'ev', '复盘', '记录品牌升级清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 75, 'extra', '表达', '对着镜子讲：我的品牌代表什么，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 76, 11, 3, '跨平台扩张', '不只在一个池子');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 76, 'am', '学习', '学习跨平台扩张：B站/公众号/知乎', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 76, 'pm', '实战', '选 1 个新平台深耕，迁移优质内容', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 76, 'ev', '复盘', '记录新平台起号数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 76, 'extra', '表达', '口述：我为什么选这个新平台，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 77, 11, 3, '影响力放大', '被行业看见');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 77, 'am', '学习', '学习影响力放大：被采访/做嘉宾/写专栏', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 77, 'pm', '实战', '主动联系 1 个行业媒体/播客投稿或求访', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 77, 'ev', '复盘', '记录影响力动作清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 77, 'extra', '表达', '对着手机讲：我想被谁看见为什么，录音（练愿景表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 78, 11, 3, '团队化评估', '一个人到小团队');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 78, 'am', '学习', '学习自媒体团队化：助理/剪辑/运营', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 78, 'pm', '实战', '评估自己是否需要及能负担团队', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 78, 'ev', '复盘', '记录可外包的事项清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 78, 'extra', '表达', '口述：我要不要招人，理由是___，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 79, 11, 3, '数据复盘', '90 天中段检查');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 79, 'am', '学习', '分析全部变现数据，算月收入', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 79, 'pm', '实战', '对照阶段三目标，找差距', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 79, 'ev', '复盘', '写中段复盘', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 79, 'extra', '表达', '录 2 分钟：我的变现数据全盘点，练''有穿透力地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 80, 11, 3, '周复盘', '品牌化推进');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 80, 'am', '学习', '回顾本周品牌/扩张/影响力动作', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 80, 'pm', '实战', '整理品牌资产清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 80, 'ev', '复盘', '写周记：从做内容到做品牌', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 80, 'extra', '表达', '对着镜头讲：我的品牌下一步，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 81, 11, 3, '表达终极训练', '把表达变成肌肉记忆');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 81, 'am', '学习', '回顾 90 天所有录音，归纳进步和残留问题', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 81, 'pm', '实战', '做一次''即兴演讲''训练：随机选题讲 2 分钟', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 81, 'ev', '复盘', '整理''我的表达进化史''', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 81, 'extra', '表达', '录 3 分钟：90 天我的表达怎么变了，练''有感染力地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 82, 12, 3, '长期规划', '把自媒体当事业');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 82, 'am', '学习', '学习自媒体长期规划：1 年/3 年目标', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 82, 'pm', '实战', '写自媒体 1 年规划（产品/收入/影响力目标）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 82, 'ev', '复盘', '记录关键里程碑', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 82, 'extra', '表达', '对着镜子讲：1 年后我的账号长什么样，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 83, 12, 3, '风险管理', '可持续比爆发重要');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 83, 'am', '学习', '学习自媒体风险：平台政策/精力/收入波动', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 83, 'pm', '实战', '制定风险预案（多平台/多收入/休息节奏）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 83, 'ev', '复盘', '记录风险管理清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 83, 'extra', '表达', '口述：我怎么避免自媒体倦怠，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 84, 12, 3, '90 天总复盘', '完整回顾');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 84, 'am', '学习', '对照 90 天目标逐项检查', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 84, 'pm', '实战', '整理 90 天内容/数据/收入总表', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 84, 'ev', '复盘', '写''90 天自媒体复盘''长文发布', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 84, 'extra', '表达', '录 3 分钟：我的 90 天自媒体之路，练''有总结力地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 85, 12, 3, '粉丝答谢', '感恩与承诺');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 85, 'am', '学习', '学习粉丝答谢的形式', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 85, 'pm', '实战', '做一场答谢直播/抽奖/感谢信', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 85, 'ev', '复盘', '记录粉丝反馈', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 85, 'extra', '表达', '对着镜头讲：感谢你们这 90 天，练''有温度地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 86, 12, 3, '变现优化', '提升单位时间收益');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 86, 'am', '学习', '分析各变现路径时薪', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 86, 'pm', '实战', '砍掉低收益动作，加码高收益', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 86, 'ev', '复盘', '记录变现优化方案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 86, 'extra', '表达', '口述：我的时间怎么分配最赚钱，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 87, 12, 3, '经验输出', '帮后来者少走弯路');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 87, 'am', '学习', '把 90 天经验整理成''内向者自媒体起步指南''', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 87, 'pm', '实战', '发布到小红书/知乎/公众号', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 87, 'ev', '复盘', '记录传播反馈', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 87, 'extra', '表达', '对着手机讲：给内向者做自媒体的 3 条建议，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 88, 12, 3, '缓冲日', '处理未尽事宜');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 88, 'am', '学习', '补完落后任务，整理素材', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 88, 'pm', '实战', '处理商务/合作收尾', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 88, 'ev', '复盘', '整理电脑文件', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 88, 'extra', '表达', '口述：我现在的心态，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 89, 12, 3, '下一程规划', '和 AI/跨境电商联动');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 89, 'am', '学习', '思考自媒体与 AI 工程师/跨境电商的联动', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 89, 'pm', '实战', '写三线协同计划（内容+技术+电商）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 89, 'ev', '复盘', '记录协同点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 89, 'extra', '表达', '对着镜子讲：我的三线作战怎么协同，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (3, 90, 12, 3, '90 天毕业', '毕业总结');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 90, 'am', '学习', '回顾整个打卡系统，导出存档', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 90, 'pm', '实战', '完成毕业总结', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 90, 'ev', '复盘', '发毕业动态', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (3, 90, 'extra', '表达', '录 3 分钟毕业感言：给 90 天前的自己，练''有力量地表达''', 0);
