SET NAMES utf8mb4;
USE roadmap;
TRUNCATE TABLE todos;
TRUNCATE TABLE plan_days;
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (0, 0, 1, '第 0 天：环境与资料准备', '开发环境全部就绪');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (1, 1, 1, 'LLM 是什么：Token 与上下文', '理解 Token / 温度 / 上下文窗口');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (2, 1, 1, 'Ollama 模型管理 + Chat API', '跑通 /api/chat 多轮对话');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (3, 1, 1, 'Prompt 工程基础', '能写出结构化 System Prompt');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (4, 1, 1, 'Prompt 输出 JSON 与解析', '稳定输出可解析 JSON');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (5, 1, 1, '上下文管理与多轮记忆', '实现带记忆的对话 CLI');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (6, 1, 1, '本地模型选型与显存/内存实测', '模型选型评测表');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (7, 1, 1, '周复盘 + 第 2 周预习', '第一周笔记 + Demo 整理');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (8, 2, 1, 'SSE 协议原理', '手写最小 SSE 服务');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (9, 2, 1, 'Ollama 流式输出对接', '打通模型流式管道');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (10, 2, 1, '流式对话组件化', 'ChatMessage 组件 + Markdown 渲染');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (11, 2, 1, 'SSE 断线重连与中断生成', '断点续流 + stop 按钮');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (12, 2, 1, 'WebSocket 双向通信', 'WS 聊天 Demo');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (13, 2, 1, '会话管理：多会话与持久化', '多会话切换');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (14, 2, 1, '周复盘 + 作品 1 骨架搭建', '作品 1 工程骨架');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (15, 3, 1, 'Function Calling 原理', '跑通第一个工具调用');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (16, 3, 1, '实用工具开发', '天气+时间+计算器 3 个工具');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (17, 3, 1, '前端工具调用 UI', '工具执行卡片');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (18, 3, 1, '对话页面打磨 Ⅰ：UI 细节', '高保真聊天界面');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (19, 3, 1, '对话页面打磨 Ⅱ：上下文面板', '参数配置面板');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (20, 3, 1, '错误处理与边界情况', '稳定可用的对话体验');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (21, 3, 1, '周复盘 + 作品 1 集成', '作品 1 功能全集成');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (22, 4, 1, '局域网访问与手机联调', '手机能打开对话平台');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (23, 4, 1, 'Tailscale 组网', '手机远程可访问');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (24, 4, 1, 'PWA 与添加到主屏', '类 App 体验');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (25, 4, 1, '作品 1 打磨：性能与体验', '首屏 1s 内');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (26, 4, 1, '作品 1 文档与 README', '完整项目文档');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (27, 4, 1, '面试话术专项：作品 1', '作品 1 讲解稿');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (28, 4, 1, '阶段一收尾：查漏补缺', '阶段一知识清单 100%');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (29, 4, 1, '缓冲日：补进度 / 深化', '追赶落后的部分');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (30, 4, 1, '求职日：简历投递第一批', '投出 20+ 简历');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (31, 5, 2, 'RAG 概念与Embedding 原理', '理解向量检索原理');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (32, 5, 2, '文档解析与切片', 'PDF→切片管道');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (33, 5, 2, 'Chroma 向量库入门', '向量入库+检索');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (34, 5, 2, '最小 RAG 问答闭环', '能答文档问题');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (35, 5, 2, '检索质量优化：混合检索', '召回率提升');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (36, 5, 2, '上传与异步入库管道', '完整入库流程');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (37, 5, 2, '周复盘：RAG 基础闭环', 'RAG 基础笔记全');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (38, 6, 2, 'Rerank 重排', '重排后精度提升');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (39, 6, 2, '查询改写与 HyDE', '复杂问题召回提升');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (40, 6, 2, '引用溯源', '回答带来源');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (41, 6, 2, '幻觉抑制', '无据不答');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (42, 6, 2, '多文档知识库管理', '多文档问答');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (43, 6, 2, '作品 2 页面开发', '作品 2 UI 完成');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (44, 6, 2, '周复盘：作品 2 联调', '作品 2 端到端可用');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (45, 7, 2, 'Agent 概念与 ReAct 模式', '手写 ReAct 循环');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (46, 7, 2, 'LangChain.js 入门', 'LC 版 ReAct');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (47, 7, 2, 'Agent 记忆模块', '短期+长期记忆');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (48, 7, 2, 'Agent 反思与自纠错', '失败重试 Agent');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (49, 7, 2, '多 Agent 协作', '两 Agent 协作 Demo');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (50, 7, 2, '结构化输出与解析', 'Agent 输出强类型');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (51, 7, 2, '周复盘：Agent 核心能力', 'Agent 笔记全+Demo 集');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (52, 8, 2, 'Dify 本地部署', 'Dify 跑起来');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (53, 8, 2, 'Dify 知识库与工作流', 'Dify 版 RAG');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (54, 8, 2, 'Dify API 集成', '前端接 Dify');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (55, 8, 2, '作品 2 打磨 Ⅰ', '引用体验优化');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (56, 8, 2, '作品 2 打磨 Ⅱ', '多格式支持');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (57, 8, 2, '作品 2 测试与文档', '验收达标');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (58, 8, 2, '面试话术专项：作品 2', '作品 2 讲解稿');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (59, 8, 2, '缓冲日：补进度', '追赶落后部分');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (60, 8, 2, '求职日：简历投递第二批', '投出 20+（AI 应用方向）');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (61, 9, 3, '工作流引擎概念', 'DAG 数据结构设计');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (62, 9, 3, '节点系统设计', '4 类基础节点');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (63, 9, 3, '执行引擎：分支与循环', '完整执行引擎');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (64, 9, 3, '执行引擎：失败重试与超时', '生产级可靠性');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (65, 9, 3, '变量系统与上下文传递', '节点间数据流');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (66, 9, 3, 'LangGraph.js 入门', 'LC 版工作流');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (67, 9, 3, '周复盘：引擎核心完成', '工作流引擎可用');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (68, 10, 3, 'Vue Flow 入门', '基础画布跑通');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (69, 10, 3, '自定义节点体系', '4 类节点卡片');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (70, 10, 3, '参数配置面板', '节点属性编辑');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (71, 10, 3, '画布数据与执行联动', '画布→引擎→画布');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (72, 10, 3, '画布体验打磨', '专业级画布');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (73, 10, 3, '模板工作流市场', '3 个预置模板');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (74, 10, 3, '周复盘：画布完成', '画布全功能可用');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (75, 11, 3, '执行监控大屏 Ⅰ：实时状态', '大屏骨架');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (76, 11, 3, '执行监控大屏 Ⅱ：可视化图表', '图表完成');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (77, 11, 3, '执行日志与历史回放', '执行记录可追溯');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (78, 11, 3, 'Tailscale 远程演示部署', '手机远程全流程');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (79, 11, 3, '作品 3 集成测试', '全链路无 bug');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (80, 11, 3, '作品 3 文档', '作品 3 README');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (81, 11, 3, '周复盘：阶段三核心完成', '三作品全可用');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (82, 12, 3, '个人主页作品集整合', '主页展示三作品');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (83, 12, 3, '简历终版打磨', '简历定稿');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (84, 12, 3, '面试题库系统准备', '高频 30 题全覆盖');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (85, 12, 3, '模拟面试 Ⅰ', '首次模拟通过');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (86, 12, 3, '模拟面试 Ⅱ + 技术补强', '二次模拟提升明显');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (87, 12, 3, '海量投递第三批', '投出 30+');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (88, 12, 3, '作品集终审 + 缓冲', '作品 100% 完成度');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (89, 12, 3, '90 天总复盘', '成长报告');
INSERT INTO plan_days (day_no, week_no, stage, theme, output) VALUES (90, 12, 3, '毕业日：全面冲刺面试', '进入面试节奏');
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (0, 'am', '理论', '安装 Ollama 并 pull qwen2.5:7b / deepseek-r1:7b', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (0, 'am', '理论', '安装 Tailscale，手机电脑同账号登录', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (0, 'pm', '实战', '创建 roadmap-demo 工程仓库（Vite + Vue3 + TS）推送到 Gitee/GitHub', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (0, 'pm', '实战', '浏览器跑通 Ollama /api/generate 第一个请求', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (0, 'ev', '复盘', '收藏学习资料：LangChain.js 文档 / Dify 文档 / B 站教程清单', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (0, 'ev', '复盘', '写 Day0 环境清单 README 存入仓库', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (1, 'am', '理论', '看视频：LLM 工作原理（Token、采样、temperature）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (1, 'am', '理论', '读 Ollama 官方文档 API 章节', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (1, 'pm', '实战', '用 curl 调 Ollama /api/generate，分别测 temperature=0 和 1.5 各 5 次', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (1, 'pm', '实战', '对比输出差异并截图记录到笔记', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (1, 'ev', '复盘', '整理今日概念笔记：Token 计费 / 上下文窗口对业务的限制', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (1, 'extra', '素材', '更新简历草稿：加一条『本地大模型调用经验』', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (2, 'am', '理论', '读 Ollama 文档：模型列表 / Modelfile / 多模态模型', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (2, 'pm', '实战', '用 Postman/curl 跑通 /api/chat 多轮对话（带 messages 数组）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (2, 'pm', '实战', '试装 deepseek-r1:7b，观察思维链输出的 JSON 字段', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (2, 'ev', '复盘', '笔记：generate 与 chat 两个接口的差异和适用场景', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (3, 'am', '理论', '学 Prompt 技巧：角色设定 / few-shot / 输出格式约束', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (3, 'pm', '实战', '给 qwen2.5:7b 写一个『工业客服』System Prompt（角色+边界+输出 JSON）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (3, 'pm', '实战', '测 10 组问题，迭代 3 版 Prompt 并记录每版效果', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (3, 'ev', '复盘', '笔记：Prompt 迭代记录表（版本/改动/效果对比）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (4, 'am', '理论', '学 format=json 参数与 JSON Schema 约束', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (4, 'pm', '实战', '让模型稳定输出 JSON：用 format 参数 + 失败重试逻辑写一个小工具函数', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (4, 'pm', '实战', '写 TS 类型定义，手写 JSON 到类型的校验函数', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (4, 'ev', '复盘', '笔记：大模型输出解析的 3 种容错方案', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (5, 'am', '理论', '学上下文裁剪策略：滑动窗口 / 摘要压缩', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (5, 'pm', '实战', '写 Node 脚本：维护 messages 数组实现 20 轮记忆 + 超长自动摘要压缩', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (5, 'ev', '复盘', '笔记：多轮对话的上下文管理方案对比', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (6, 'am', '理论', '了解常见开源模型：qwen / deepseek / llama 参数量与硬件要求', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (6, 'pm', '实战', '实测 3 个模型在 32G 笔记本上的首 token 延迟和速度，填评测表', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (6, 'ev', '复盘', '本周复盘：输出《第一周学习笔记》md 存仓库', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (7, 'am', '理论', '过一遍本周所有笔记，查漏补缺', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (7, 'pm', '实战', '把本周脚本整理成 ollama-basics/ 目录，写 README', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (7, 'pm', '实战', '预习：HTTP SSE 协议规范 10 分钟入门', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (7, 'ev', '复盘', '口述录制 5 分钟：『本地大模型 API 调用』给自己回听', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (8, 'am', '理论', '学 SSE 协议：text/event-stream / data: 格式 / 自动重连机制', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (8, 'pm', '实战', '用 Node 原生 http 写一个最小 SSE 服务器（每秒推一条）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (8, 'pm', '实战', '浏览器 EventSource 连上并打印到页面', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (8, 'ev', '复盘', '笔记：SSE 报文格式手绘图（拍照存仓库）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (9, 'am', '理论', '读 Ollama 文档 stream 参数，理解逐 token JSON 流', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (9, 'pm', '实战', 'Node 接收 Ollama NDJSON 流并转成标准 SSE 推给浏览器', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (9, 'pm', '实战', '前端实现打字机效果组件 v1', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (9, 'ev', '复盘', '笔记：NDJSON → SSE 的转换链路图', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (10, 'am', '理论', '看别人的开源聊天 UI 源码（如 chatgpt-web）结构', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (10, 'pm', '实战', 'Vue3 实现 ChatList + ChatInput + 流式气泡组件', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (10, 'pm', '实战', '接入 markdown-it 渲染 AI 回复的代码块', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (10, 'ev', '复盘', '笔记：流式渲染的防抖与滚动跟随技巧', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (11, 'am', '理论', '学 EventSource 的 onerror 与 lastEventId 机制', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (11, 'pm', '实战', '实现 SSE 断线自动重连 + 服务端 lastEventId 续传', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (11, 'pm', '实战', '前端『停止生成』按钮（AbortController 中断流）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (11, 'ev', '复盘', '笔记：AbortController 在流式请求中的用法', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (12, 'am', '理论', '学 WebSocket：握手升级 / 心跳 / 与 SSE 适用场景对比', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (12, 'pm', '实战', '用 ws 库写 WS 服务端，实现浏览器↔Node 双向消息', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (12, 'pm', '实战', '把 WS 接到 Ollama 实现双向流式对话', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (12, 'ev', '复盘', '背诵面试话术 Q1：SSE vs WebSocket（口述 3 遍）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (13, 'am', '理论', '设计会话数据结构：会话列表 / 消息存储方案（低配：JSON 文件）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (13, 'pm', '实战', '实现左侧会话列表 + 新建/切换/删除会话', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (13, 'pm', '实战', '会话持久化到本地 JSON 文件，刷新不丢', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (13, 'ev', '复盘', '笔记：会话存储从 JSON 文件到 SQLite/MySQL 的迁移思路', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (14, 'am', '理论', '过本周笔记，重点复盘 SSE 重连方案', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (14, 'pm', '实战', '创建 chat-platform 工程骨架（前后端目录 / 路由 / 布局）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (14, 'pm', '实战', '把本周的流式对话组件迁移进去', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (14, 'ev', '复盘', '口述录制：『流式输出完整链路』5 分钟', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (15, 'am', '理论', '学 Function Calling：tools 定义 / 模型决策 / 二次调用闭环', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (15, 'pm', '实战', '用 curl 调 Ollama tools 参数，实现『查天气』函数的完整闭环', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (15, 'pm', '实战', '在 Node 里封装工具注册器 registerTool()', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (15, 'ev', '复盘', '笔记：函数调用三阶段流程图（模型选工具→执行→回填结果）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (16, 'am', '理论', '学并行工具调用：一次返回多个 tool_calls 的处理', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (16, 'pm', '实战', '实现 3 个本地工具：真实天气 API / 系统时间 / 数学表达式计算', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (16, 'pm', '实战', '处理模型一次要求调用多个工具的情况', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (16, 'ev', '复盘', '笔记：工具 schema 设计的最佳实践', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (17, 'am', '理论', '看主流 AI 产品工具调用的 UI 形态（折叠卡片/过程展示）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (17, 'pm', '实战', '前端实现工具调用过程卡片：调用中→执行中→完成 3 态', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (17, 'pm', '实战', '流式输出中穿插工具卡片的排版处理', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (17, 'ev', '复盘', '笔记：AI 产品的『过程可视化』设计模式', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (18, 'am', '理论', '学移动端 H5 聊天布局适配（安全区 / 软键盘弹起）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (18, 'pm', '实战', '消息气泡重新设计（头像/时间/复制按钮/代码高亮）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (18, 'pm', '实战', '移动端 media query 适配 + 软键盘体验处理', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (18, 'ev', '复盘', '笔记：H5 聊天页软键盘踩坑记录', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (19, 'am', '理论', '学 temperature / top_p / system prompt 的产品化暴露方式', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (19, 'pm', '实战', '实现右侧设置面板：模型切换 / 温度 / System Prompt 编辑', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (19, 'pm', '实战', '参数变化即时生效（透传到后端）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (19, 'ev', '复盘', '笔记：AI 产品参数面板的常见交互', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (20, 'am', '理论', '梳理失败场景：模型超时 / Ollama 未启动 / 网络断开', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (20, 'pm', '实战', '统一错误处理：重试按钮 / 友好提示 / 服务不可达引导', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (20, 'pm', '实战', '长对话超上下文窗口的自动裁剪', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (20, 'ev', '复盘', '笔记：AI 应用错误处理清单', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (21, 'am', '理论', '复盘本周：工具调用闭环有没有断点', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (21, 'pm', '实战', '作品 1 集成测试：流式对话+工具调用+多会话全链路走通', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (21, 'pm', '实战', 'git tag v0.1 并部署本地常驻', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (21, 'ev', '复盘', '口述录制：『Function Calling 从原理到实现』', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (22, 'am', '理论', '学 Vite host 配置与局域网 IP 访问原理', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (22, 'pm', '实战', '配置 dev/preview 服务监听 0.0.0.0', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (22, 'pm', '实战', '手机连同一 WiFi 实测对话 + 工具调用', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (22, 'ev', '复盘', '笔记：前端本地服务的局域网暴露方案', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (23, 'am', '理论', '学 Tailscale：虚拟局域网原理 / 设备管理', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (23, 'pm', '实战', '电脑与手机组网，手机用 100.x IP 访问对话平台', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (23, 'pm', '实战', '在外面用 4G 网络测试远程对话', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (23, 'ev', '复盘', '笔记：内网穿透三方案对比（Tailscale/frp/云服务器）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (24, 'am', '理论', '学 PWA manifest 与图标配置', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (24, 'pm', '实战', '给作品 1 配 manifest + 图标，手机添加到主屏幕', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (24, 'pm', '实战', '处理 iOS Safari 的 PWA 兼容差异', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (24, 'ev', '复盘', '笔记：PWA 在 AI 工具类产品的价值', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (25, 'am', '理论', '学性能分析：Lighthouse / Network 面板', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (25, 'pm', '实战', '路由懒加载 + 组件按需加载优化首屏', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (25, 'pm', '实战', '长列表虚拟滚动优化会话消息渲染', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (25, 'ev', '复盘', '笔记：聊天类应用性能优化清单', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'am', '理论', '看优秀开源项目 README 的结构（截图/架构图/快速开始）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'pm', '实战', '写作品 1 README：功能截图 + 架构图 + 快速启动 + 技术栈', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'pm', '实战', '录 60 秒功能演示 GIF', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', '更', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', '新', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', '简', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', '历', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', '：', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', '作', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', '品', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', ' ', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', '1', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', ' ', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', '条', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', '目', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', '按', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', ' ', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', 'S', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', 'T', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', 'A', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', 'R', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', ' ', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', '法', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', '则', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', '写', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', ' ', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', '4', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', ' ', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (26, 'ev', '复盘', '行', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (27, 'am', '理论', '整理作品 1 可能被问的 10 个问题', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (27, 'pm', '实战', '写出每个问题的回答要点，重点：SSE 断线重连 / 工具调用闭环', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (27, 'pm', '实战', '对着镜子口述完整项目介绍 3 遍', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (27, 'ev', '复盘', '背诵面试话术 Q1（SSE vs WebSocket）+ 工具调用原理', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (28, 'am', '理论', '过阶段一全部笔记，标出薄弱点', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (28, 'pm', '实战', '针对薄弱点重做 2 个练习', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (28, 'pm', '实战', '阶段一所有代码整理入库打 tag v1.0', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (28, 'ev', '复盘', '输出《阶段一总结》：会什么 / 能做什么 / 作品链接', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (29, 'am', '理论', '按需：补未完成的学习任务', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (29, 'pm', '实战', '按需：修作品 1 遗留 bug / 优化细节', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (29, 'ev', '复盘', '按需：把没录的讲解视频补上', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (30, 'am', '理论', '浏览 Boss 直聘 AI 前端岗位 JD，提炼高频关键词', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (30, 'pm', '实战', '简历加入作品 1 + 关键词优化，导出 PDF', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (30, 'pm', '实战', '投递普通 AI 前端岗 20+ 家，记录进展表', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (30, 'ev', '复盘', '建立求职追踪表：公司/岗位/状态/反馈', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (31, 'am', '理论', '学 RAG 为什么存在：幻觉 / 知识时效 / 私有知识', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (31, 'pm', '实战', '跑通 OpenAI 兼容 embedding 接口（Ollama 或免费方案）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (31, 'pm', '实战', '手算两段文本的余弦相似度加深理解', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (31, 'ev', '复盘', '笔记：RAG 与微调的选型对比', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (32, 'am', '理论', '学切片策略：固定长度 / 递归切片 / 重叠窗口 / 语义切片', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (32, 'pm', '实战', '用 pdf-parse 解析 PDF 提取文本', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (32, 'pm', '实战', '实现递归切片函数（chunk 512 / overlap 64）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (32, 'ev', '复盘', '笔记：切片大小对召回质量的影响', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (33, 'am', '理论', '读 Chroma 文档：collection / add / query', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (33, 'pm', '实战', 'Docker 或 npm 方式跑起 Chroma', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (33, 'pm', '实战', '把昨日切片全部向量化入库，实现 query 检索 Top-5', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (33, 'ev', '复盘', '笔记：向量库 CRUD 与元数据过滤', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (34, 'am', '理论', '学 RAG Prompt 模板：上下文注入 + 引用要求', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (34, 'pm', '实战', '实现：问题→检索→拼 Prompt→LLM 回答 完整闭环', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (34, 'pm', '实战', '测 20 个基于文档的问题，记录答对率', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (34, 'ev', '复盘', '笔记：RAG 上下文注入的 Prompt 模板沉淀', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (35, 'am', '理论', '学混合检索：BM25 关键词 + 向量语义互补', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (35, 'pm', '实战', '实现 BM25（rank-bm25 或 minisearch）与向量检索合并', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (35, 'pm', '实战', '对比纯向量 vs 混合检索的召回效果', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (35, 'ev', '复盘', '笔记：混合检索的权重融合公式', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (36, 'am', '理论', '学文件上传：multer + 前端分片上传', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (36, 'pm', '实战', '实现前端上传 PDF→后端解析→切片→入库 全流程', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (36, 'pm', '实战', '入库进度条 + 重复文件检测', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (36, 'ev', '复盘', '笔记：大文件入库的队列与去重设计', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (37, 'am', '理论', '复盘：RAG 全流程图默画一遍', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (37, 'pm', '实战', '把本周 RAG 代码整理成 rag-core/ 模块', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (37, 'pm', '实战', '预习：Rerank 重排概念', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (37, 'ev', '复盘', '口述录制：『RAG 从 0 到 1 的完整链路』', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (38, 'am', '理论', '学 Cross-Encoder 重排原理 vs 双塔检索', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (38, 'pm', '实战', '接入免费重排方案（LLM 打分或本地 bge-reranker）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (38, 'pm', '实战', '对比重排前后 Top-5 命中率', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (38, 'ev', '复盘', '笔记：Rerank 的成本与延迟权衡', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (39, 'am', '理论', '学查询改写：拆解多问 / 同义扩写 / HyDE 假设文档', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (39, 'pm', '实战', '实现 HyDE：先让 LLM 生成假设答案再拿去检索', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (39, 'pm', '实战', '对比直接检索 vs HyDE 在 10 个复杂问题上的效果', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (39, 'ev', '复盘', '笔记：Query Rewrite 三板斧适用场景', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (40, 'am', '理论', '学引用溯源方案：chunk 元数据回链 / 引用标注格式', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (40, 'pm', '实战', '每个 chunk 携带页码/段落元数据，回答时输出 [1][2] 引用', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (40, 'pm', '实战', '前端渲染引用角标，点击跳转原文出处', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (40, 'ev', '复盘', '笔记：可解释 AI 问答的引用设计', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (41, 'am', '理论', '学幻觉抑制：相似度阈值 / 『不知道』兜底 / 检索质量自检', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (41, 'pm', '实战', '实现低置信度兜底话术（检索分数低于阈值拒答）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (41, 'pm', '实战', '测无文档支持的问题 10 个，验证不乱编', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (41, 'ev', '复盘', '背诵面试话术 Q2：RAG 防幻觉（口述 3 遍）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (42, 'am', '理论', '学多文档路由：按文档过滤 / 文档级权限', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (42, 'pm', '实战', '实现知识库管理页：多 PDF 上传 / 列表 / 删除', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (42, 'pm', '实战', '按文档 scope 检索，隔离不同手册', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (42, 'ev', '复盘', '笔记：企业级知识库的权限与隔离设计', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (43, 'am', '理论', '设计作品 2 页面结构：上传区/对话区/引用侧栏', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (43, 'pm', '实战', 'Vue3 实现作品 2 完整 UI（沿用作品 1 组件）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (43, 'pm', '实战', '接入 RAG 后端全部接口', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (43, 'ev', '复盘', '笔记：组件复用率统计（作品1复用了多少）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (44, 'am', '理论', '复盘本周检索优化链路', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (44, 'pm', '实战', '作品 2 端到端测试：上传→提问→引用→追问 20 轮', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (44, 'pm', '实战', '修复联调 bug，git tag v0.2', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (44, 'ev', '复盘', '口述录制：『RAG 优化三板斧：重排/改写/溯源』', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (45, 'am', '理论', '学 Agent 四大模块：规划/记忆/工具/反思，ReAct 推理模式', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (45, 'pm', '实战', '不依赖框架手写 ReAct 循环：思考→行动→观察→再思考', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (45, 'pm', '实战', '用 2 个工具跑通『搜索+计算』组合任务', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (45, 'ev', '复盘', '笔记：ReAct 的 Prompt 结构拆解', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (46, 'am', '理论', '读 LangChain.js 文档：Model / Prompt / Chain 抽象', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (46, 'pm', '实战', '用 LangChain.js 重写昨日 ReAct Agent', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (46, 'pm', '实战', '对比手写版和框架版的代码量与可控性', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (46, 'ev', '复盘', '笔记：LangChain 核心抽象关系图', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (47, 'am', '理论', '学记忆方案：BufferMemory / 摘要记忆 / 向量长期记忆', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (47, 'pm', '实战', '给 Agent 加短期对话记忆 + 超长自动摘要', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (47, 'pm', '实战', '实现向量长期记忆（用户偏好持久化）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (47, 'ev', '复盘', '笔记：记忆的三层架构设计', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (48, 'am', '理论', '学 Reflexion：失败→反思→修正重试', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (48, 'pm', '实战', '实现工具调用失败后的自动反思重试（最多 3 次）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (48, 'pm', '实战', '构造 5 个必失败场景验证自纠错', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (48, 'ev', '复盘', '笔记：Agent 可靠性设计的常用手段', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (49, 'am', '理论', '学多 Agent 模式：主从 / 辩论 / 流水线', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (49, 'pm', '实战', '实现『规划者+执行者』双 Agent：一个拆任务一个执行', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (49, 'pm', '实战', '跑通一个多步骤工业巡检任务', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (49, 'ev', '复盘', '笔记：多 Agent 的任务传递与状态共享', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (50, 'am', '理论', '学 StructuredOutputParser 与 JSON Schema', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (50, 'pm', '实战', 'Agent 输出强制结构化（zod schema 校验）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (50, 'pm', '实战', '解析失败自动修复重试', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (50, 'ev', '复盘', '笔记：LLM 输出工程化校验方案', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (51, 'am', '理论', '复盘：Agent 四大模块全部笔记串联', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (51, 'pm', '实战', '本周 Agent Demo 整理成 agent-lab/ 目录', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (51, 'pm', '实战', '预习：Dify 架构介绍文档', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (51, 'ev', '复盘', '口述录制：『从 ReAct 到多 Agent 协作』', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (52, 'am', '理论', '读 Dify 文档：Docker Compose 部署架构', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (52, 'pm', '实战', 'Docker 部署 Dify 社区版，配置 Ollama 作为模型供应商', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (52, 'pm', '实战', '熟悉 Dify 界面：知识库/工作流/应用', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (52, 'ev', '复盘', '笔记：Dify 组件架构图（docker ps 每个容器的作用）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (53, 'am', '理论', '学 Dify 工作流画布：节点类型/变量传递', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (53, 'pm', '实战', '用 Dify 搭一个 RAG 应用（复用作品 2 文档）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (53, 'pm', '实战', 'Dify 工作流实现分支：文档类型判断走不同链路', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (53, 'ev', '复盘', '笔记：Dify 工作流与手写代码的边界', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (54, 'am', '理论', '读 Dify OpenAPI：应用 API / 会话 API', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (54, 'pm', '实战', '作品 2 增加『Dify 模式』开关：前端直接调 Dify API', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (54, 'pm', '实战', '对比自研 RAG 与 Dify 的效果差异并记录', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (54, 'ev', '复盘', '笔记：自研 vs 平台化的选型话术', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (55, 'am', '理论', '看竞品（Coze/Kimi 文件问答）的引用交互', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (55, 'pm', '实战', '引用高亮原文段落 + 侧栏原文预览', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (55, 'pm', '实战', '回答流式输出时实时渲染引用角标', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (55, 'ev', '复盘', '笔记：文档问答产品的引用交互对比', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (56, 'am', '理论', '学 docx/xlsx 解析方案', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (56, 'pm', '实战', '支持 Word 和 Excel 文档入库', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (56, 'pm', '实战', '扫描版 PDF 识别的方案调研（OCR 路线记录）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (56, 'ev', '复盘', '笔记：多格式文档解析踩坑记录', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'am', '理论', '用 3 份真实工业手册做验收测试', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'pm', '实战', '跑验收标准：专业问题能答、无文档不乱编、引用可溯源', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'pm', '实战', '写作品 2 README + 架构图 + 演示 GIF', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', '更', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', '新', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', '简', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', '历', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', '：', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', '作', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', '品', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', ' ', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', '2', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', ' ', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', '条', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', '目', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', ' ', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', '+', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', ' ', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', 'R', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', 'A', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', 'G', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', ' ', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', '关', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', '键', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (57, 'ev', '复盘', '词', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (58, 'am', '理论', '整理作品 2 高频面试题 10 个', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (58, 'pm', '实战', '重点准备：切片策略 / 混合检索 / 防幻觉兜底', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (58, 'pm', '实战', '口述完整讲解 3 遍并录音回听', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (58, 'ev', '复盘', '背诵面试话术 Q2 完整版', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (59, 'am', '理论', '按需补未完成任务', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (59, 'pm', '实战', '按需修 bug / 优化', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (59, 'ev', '复盘', '按需补录制', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (60, 'am', '理论', '看 AI 应用/SaaS 厂商 JD，对齐关键词', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (60, 'pm', '实战', '简历更新作品 2，投递 AI 应用/文档智能方向 20+', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (60, 'pm', '实战', '整理第一批投递的反馈与复盘', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (60, 'ev', '复盘', '求职追踪表更新，分析哪些 JD 回应率高', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (61, 'am', '理论', '学工作流基础：DAG / 拓扑排序 / 分支 / 循环 / 失败重试', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (61, 'pm', '实战', '设计工作流 JSON Schema：节点+边+变量', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (61, 'pm', '实战', '手写拓扑排序执行器跑通 3 节点示例', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (61, 'ev', '复盘', '笔记：工作流引擎核心概念地图', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (62, 'am', '理论', '学节点抽象：统一输入输出契约', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (62, 'pm', '实战', '实现 LLM 节点 / 工具节点 / 条件分支节点 / 结束节点', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (62, 'pm', '实战', '每个节点的参数 Schema 与执行接口', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (62, 'ev', '复盘', '笔记：节点多态设计的 TS 类型抽象', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (63, 'am', '理论', '学条件跳转与循环节点的实现原理', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (63, 'pm', '实战', '实现条件分支（LLM 判断走哪条边）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (63, 'pm', '实战', '实现循环节点（最大次数+满足条件退出）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (63, 'ev', '复盘', '笔记：有环图的执行终止条件设计', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (64, 'am', '理论', '学重试策略：指数退避 / 超时熔断', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (64, 'pm', '实战', '节点级重试（次数+退避）与全局超时控制', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (64, 'pm', '实战', '构造失败场景验证：重试→降级→终止', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (64, 'ev', '复盘', '笔记：工作流容错设计清单', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (65, 'am', '理论', '学变量引用语法：{{node_id.output.xxx}}', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (65, 'pm', '实战', '实现变量解析器：节点输出注入下游节点参数', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (65, 'pm', '实战', '全局上下文与节点私有变量隔离', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (65, 'ev', '复盘', '笔记：低代码平台的变量系统设计', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (66, 'am', '理论', '读 LangGraph.js 文档：StateGraph / 节点 / 边', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (66, 'pm', '实战', '用 LangGraph.js 实现等价的分支循环工作流', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (66, 'pm', '实战', '对比自研引擎与 LangGraph 的能力差异', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (66, 'ev', '复盘', '笔记：LangGraph 状态图 vs 自研 DAG 选型', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (67, 'am', '理论', '复盘：引擎全部概念默写链路', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (67, 'pm', '实战', '引擎集成测试：一个完整工业场景流（报障→分类→处理）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (67, 'pm', '实战', 'git tag engine-v1', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (67, 'ev', '复盘', '口述录制：『我如何设计一个工作流引擎』', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (68, 'am', '理论', '读 Vue Flow 文档：节点/边/画布事件', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (68, 'pm', '实战', 'Vue3 集成 Vue Flow，实现节点拖拽添加与连线', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (68, 'pm', '实战', '自定义第一个节点卡片（LLM 节点）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (68, 'ev', '复盘', '笔记：Vue Flow 核心 API 速查表', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (69, 'am', '理论', '学自定义节点渲染与端口（Handle）设计', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (69, 'pm', '实战', '实现 LLM/工具/分支/结束 4 类节点的专属卡片', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (69, 'pm', '实战', '节点状态样式：待执行/执行中/成功/失败', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (69, 'ev', '复盘', '笔记：节点卡片的状态机设计', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (70, 'am', '理论', '学动态表单：按节点类型渲染不同表单', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (70, 'pm', '实战', '点击节点右侧弹出配置面板（Prompt/参数/变量引用）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (70, 'pm', '实战', '表单校验与变量选择器', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (70, 'ev', '复盘', '笔记：低代码配置面板的动态表单方案', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (71, 'am', '理论', '设计画布 JSON 与引擎 Schema 的转换层', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (71, 'pm', '实战', '画布保存→序列化为工作流 JSON→调执行引擎', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (71, 'pm', '实战', '执行时节点状态实时回显到画布（高亮当前节点）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (71, 'ev', '复盘', '笔记：画布与引擎的数据流架构图', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (72, 'am', '理论', '学画布高级功能：小地图/对齐/快捷键/自动布局', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (72, 'pm', '实战', '实现小地图 + 网格对齐 + 删除/复制快捷键', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (72, 'pm', '实战', '边删除、节点右键菜单、框选批量操作', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (72, 'ev', '复盘', '笔记：对标 Dify/n8n 的画布交互差距清单', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (73, 'am', '理论', '学模板化：把典型场景固化为可复用工作流', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (73, 'pm', '实战', '内置 3 个工业模板：设备报障/文档审核/日报生成', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (73, 'pm', '实战', '模板一键载入画布', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (73, 'ev', '复盘', '笔记：行业模板的抽象方法', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (74, 'am', '理论', '复盘：画布→配置→执行→回显全链路', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (74, 'pm', '实战', '画布全功能回归测试 + bug 修复', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (74, 'pm', '实战', '预习：SSE 节点状态推送方案', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (74, 'ev', '复盘', '口述录制：『拖拽画布的 6 大模块』（背诵面试话术 Q5）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (75, 'am', '理论', '学大屏布局：Grid 布局与数据可视化选型', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (75, 'pm', '实战', '实现监控大屏骨架：执行列表/成功率/耗时统计', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (75, 'pm', '实战', 'SSE 实时推送节点执行事件到大屏', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (75, 'ev', '复盘', '笔记：实时大屏的数据推送架构', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (76, 'am', '理论', '学 ECharts 基础：折线/柱状/仪表盘', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (76, 'pm', '实战', '接入 ECharts：节点耗时分布/成功率趋势/Token 消耗', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (76, 'pm', '实战', '大屏自动轮播与定时刷新', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (76, 'ev', '复盘', '笔记：监控指标体系设计（哪些指标有价值）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (77, 'am', '理论', '学执行记录持久化与查询设计', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (77, 'pm', '实战', '每次执行落库（节点级日志/输入输出/耗时）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (77, 'pm', '实战', '执行历史列表 + 点开回放节点流转过程', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (77, 'ev', '复盘', '笔记：可观测性三支柱在工作流里的落地', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (78, 'am', '理论', '学生产部署：Node 常驻 + 进程守护', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (78, 'pm', '实战', '作品 3 整套（前端+后端+引擎）本机部署为常驻服务', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (78, 'pm', '实战', '手机经 Tailscale 远程完整演示：建流→执行→大屏', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (78, 'ev', '复盘', '笔记：面试现场远程演示的应急预案（断网/延迟）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (79, 'am', '理论', '梳理作品 3 全部功能清单做验收表', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (79, 'pm', '实战', '逐项验收测试：15+ 功能点全部通过', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (79, 'pm', '实战', '性能实测：10 节点工作流端到端耗时记录', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (79, 'ev', '复盘', '背诵面试话术 Q4：Tailscale 远程方案（口述 3 遍）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'am', '理论', '复盘优秀 README 的结构', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'pm', '实战', '写作品 3 README：架构图（画布/引擎/大屏三层）+ 快速开始', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'pm', '实战', '录作品 3 完整演示视频（3 分钟）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', '更', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', '新', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', '简', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', '历', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', '：', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', '作', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', '品', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', ' ', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', '3', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', ' ', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', '按', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', '核', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', '心', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', '项', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', '目', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', '格', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', '式', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', '写', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (80, 'ev', '复盘', '满', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (81, 'am', '理论', '复盘：三阶段所有知识体系串一遍', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (81, 'pm', '实战', '三个作品一起跑：对话平台+文档问答+工作流平台 同时在线', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (81, 'pm', '实战', '检查 Tailscale 远程全部可访问', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (81, 'ev', '复盘', '口述录制：『三个作品的定位与差异』', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (82, 'am', '理论', '规划个人主页作品集区块的信息架构', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (82, 'pm', '实战', '把三个作品接入个人主页（截图/演示视频/远程入口）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (82, 'pm', '实战', '作品集页移动端适配', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (82, 'ev', '复盘', '笔记：作品集的叙事顺序（由浅入深）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (83, 'am', '理论', '对比 10 份优秀 AI 前端简历的结构', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (83, 'pm', '实战', '简历终版：3 个 AI 作品 + 量化数据 + 关键词对齐 JD', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (83, 'pm', '实战', '两个版本：AI 前端版 / AI 应用版', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (83, 'ev', '复盘', '求职追踪表：第三批目标公司清单 50 家', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (84, 'am', '理论', '收集 AI 前端高频面试题 30 道（八股+项目）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (84, 'pm', '实战', '逐题写答案要点，重点：SSE/RAG/Agent/画布四大主题', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (84, 'pm', '实战', '5 道核心题写成完整口述稿', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (84, 'ev', '复盘', '背诵面试话术 Q1-Q5 全部（每天轮一遍）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (85, 'am', '理论', '准备模拟面试环境（自录/找朋友）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (85, 'pm', '实战', '完整模拟 45 分钟：自我介绍+项目深挖+八股', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (85, 'pm', '实战', '回看录像，记录卡壳的 10 个点并逐个补', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (85, 'ev', '复盘', '笔记：模拟面试暴露的弱点清单', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (86, 'am', '理论', '针对弱点清单补学', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (86, 'pm', '实战', '第二轮模拟面试，对比首轮表现', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (86, 'pm', '实战', '技术弱点专项突破（随机抽 3 个补强）', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (86, 'ev', '复盘', '更新弱点清单：关闭已解决项', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (87, 'am', '理论', '批量投递：工业云/智能制造/工业互联网/Agent 平台', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (87, 'pm', '实战', '投递 30+ 并做好跟进记录', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (87, 'pm', '实战', '准备各公司定制化开场白', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (87, 'ev', '复盘', '求职追踪表更新到最新状态', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (88, 'am', '理论', '终审清单：三作品功能/文档/远程演示逐项检查', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (88, 'pm', '实战', '修复终审发现的所有问题', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (88, 'pm', '实战', '补齐未完成的任何任务', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (88, 'ev', '复盘', '整理 90 天学习总笔记目录', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (89, 'am', '理论', '复盘：90 天前 vs 90 天后的能力对比表', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (89, 'pm', '实战', '输出《90 天转型总结》：技能栈+作品集+方法论', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (89, 'pm', '实战', '整理可对外分享的文章素材', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (89, 'ev', '复盘', '笔记：下一阶段（入职后）的学习方向规划', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (90, 'am', '理论', '最后过一遍全部面试话术', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (90, 'pm', '实战', '三个项目口述各 5 分钟版本/10 分钟版本各练 2 遍', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (90, 'pm', '实战', '确认 Tailscale 演示环境万无一失', 0);
INSERT INTO todos (day_no, slot, slot_name, content, done) VALUES (90, 'ev', '复盘', '庆祝 90 天毕业 🎉 保持每日刷题+投递节奏', 0);