INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 1, 1, 1, '跨境 B2B 认知', '理解 Alibaba.com 生态');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 1, 'am', '学习', '学习 B2B vs B2C 差异，理解 Alibaba.com 买家画像（海外批发商/工程商）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 1, 'pm', '实战', '注册 Alibaba.com 账号，浏览同行业店铺 20 家，记录模式', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 1, 'ev', '复盘', '整理 B2B 跨境建材的机遇与坑', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 1, 'extra', '表达', '对着手机讲：为什么建材适合做 Alibaba B2B，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 2, 1, 1, '选品与定位', '确定主打品类');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 2, 'am', '学习', '学习选品方法：看需求/竞争/利润/物流适配', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 2, 'pm', '实战', '分析手头货源（吊顶/线条/角花），选 3 个主推品类', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 2, 'ev', '复盘', '记录选品理由表（品类-需求-利润-物流）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 2, 'extra', '表达', '口述：我为什么选这 3 个品类，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 3, 1, 1, '市场调研', '摸清海外需求');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 3, 'am', '学习', '学习用 Alibaba.com 搜索栏/Google Trends 调研海外需求', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 3, 'pm', '实战', '查 5 个目标国家（中东/东南亚/非洲）的建材进口数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 3, 'ev', '复盘', '记录目标市场清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 3, 'extra', '表达', '对着手机讲：我的货最可能卖给哪个国家，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 4, 1, 1, '竞品分析', '向同行学习');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 4, 'am', '学习', '学习竞品分析维度：价格/MOQ/主图/详情/评价', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 4, 'pm', '实战', '深扒 5 家头部同行店铺，记录优劣势', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 4, 'ev', '复盘', '整理竞品对标表', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 4, 'extra', '表达', '口述：头部同行做得好和差在哪，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 5, 1, 1, '开店资质准备', '备齐开店材料');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 5, 'am', '学习', '学习 Alibaba.com 金牌供应商开店要求：营业执照/产能/认证', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 5, 'pm', '实战', '整理开店所需资料清单，开始办缺失的认证', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 5, 'ev', '复盘', '记录资料办理进度', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 5, 'extra', '表达', '对着手机讲：开店要准备什么，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 6, 1, 1, '店铺基础装修', '门面像样');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 6, 'am', '学习', '学习店铺装修：Logo/Banner/公司介绍/产能展示', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 6, 'pm', '实战', '准备店铺视觉素材，写英文公司简介', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 6, 'ev', '复盘', '记录店铺装修 checklist', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 6, 'extra', '表达', '口述：用英文介绍我的公司，录音（练英文表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 7, 1, 1, '周复盘', '开店准备就绪');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 7, 'am', '学习', '回顾本周调研和准备', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 7, 'pm', '实战', '确认开店资料齐全', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 7, 'ev', '复盘', '写周记：建材出海第一周', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 7, 'extra', '表达', '录 2 分钟：我的出海计划，练''有方向地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 8, 2, 1, '开店实操', '提交开店申请');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 8, 'am', '学习', '学习开店流程和审核要点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 8, 'pm', '实战', '提交 Alibaba.com 店铺申请，上传全部资料', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 8, 'ev', '复盘', '记录审核进度和补料事项', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 8, 'extra', '表达', '对着手机讲：开店流程我走了几步，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 9, 2, 1, '英文产品命名', '让海外买家搜得到');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 9, 'am', '学习', '学习跨境电商英文关键词挖掘（AdWord/Alibaba 搜索框）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 9, 'pm', '实战', '给 3 个品类挖 20 个英文关键词，定产品标题', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 9, 'ev', '复盘', '记录关键词库', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 9, 'extra', '表达', '口述：我的产品英文名怎么定的，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 10, 2, 1, '主图设计', '第一眼吸引买家');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 10, 'am', '学习', '学习 B2B 主图规范：白底/尺寸/卖点/Logo', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 10, 'pm', '实战', '给主打产品拍/做 5 张主图，符合规范', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 10, 'ev', '复盘', '记录主图设计 checklist', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 10, 'extra', '表达', '对着手机讲：好主图的 3 个要素，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 11, 2, 1, '详情页设计', '让买家放心下单');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 11, 'am', '学习', '学习 B2B 详情页结构：参数/工艺/案例/认证/物流', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 11, 'pm', '实战', '给主打产品写英文详情页文案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 11, 'ev', '复盘', '记录详情页模板', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 11, 'extra', '表达', '口述：详情页要回答买家什么问题，录音（练英文表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 12, 2, 1, '价格与 MOQ', 'B2B 定价策略');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 12, 'am', '学习', '学习 B2B 定价：阶梯价/MOQ/FOB/利润核算', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 12, 'pm', '实战', '给主打产品定 3 档阶梯价和 MOQ，核算利润', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 12, 'ev', '复盘', '记录定价测算表', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 12, 'extra', '表达', '对着手机讲：我的定价逻辑，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 13, 2, 1, '物流方案', '建材重货怎么发');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 13, 'am', '学习', '学习建材出口物流：海运/拼箱/FOB/CIF，了解材积重', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 13, 'pm', '实战', '询价 3 家货代，对比海运到中东/东南亚的价格时效', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 13, 'ev', '复盘', '记录物流方案表', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 13, 'extra', '表达', '口述：建材海运要注意什么，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 14, 2, 1, '周复盘', '店铺就绪待上架');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 14, 'am', '学习', '回顾本周店铺搭建', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 14, 'pm', '实战', '确认主图/详情/价格/物流齐备', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 14, 'ev', '复盘', '写周记：从 0 到可上架', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 14, 'extra', '表达', '录 2 分钟：我的店铺卖点，练''有底气地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 15, 3, 1, '产品上架', '首批产品上线');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 15, 'am', '学习', '学习 Alibaba.com 上架流程和 SEO 要点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 15, 'pm', '实战', '上架首批 10 个产品，填全属性', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 15, 'ev', '复盘', '记录上架 checklist', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 15, 'extra', '表达', '对着手机讲：上架要注意什么，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 16, 3, 1, '属性与类目', '被精准搜索');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 16, 'am', '学习', '学习类目选择和属性填写对搜索的影响', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 16, 'pm', '实战', '检查并优化 10 个产品的类目和属性完整度', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 16, 'ev', '复盘', '记录属性优化清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 16, 'extra', '表达', '口述：属性填全有什么用，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 17, 3, 1, '关键词排名', '让产品靠前');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 17, 'am', '学习', '学习 Alibaba.com 搜索排名因素：标题/属性/转化/信保', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 17, 'pm', '实战', '优化产品标题和关键词，记录排名变化', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 17, 'ev', '复盘', '记录排名优化心得', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 17, 'extra', '表达', '对着手机讲：我怎么让产品排前面，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 18, 3, 1, 'RFQ 机制', '主动找买家');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 18, 'am', '学习', '学习 RFQ（询盘报价）机制：买家发需求→卖家报价', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 18, 'pm', '实战', '每天刷 RFQ 市场，找 5 条匹配需求，报价 2 条', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 18, 'ev', '复盘', '记录 RFQ 报价模板', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 18, 'extra', '表达', '口述：RFQ 怎么玩，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 19, 3, 1, '客户跟进话术', '把询盘变订单');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 19, 'am', '学习', '学习 B2B 询盘回复话术：快/专业/问对问题/促单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 19, 'pm', '实战', '写英文询盘回复模板 5 套', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 19, 'ev', '复盘', '记录询盘回复 checklist', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 19, 'extra', '表达', '对着手机用英文练询盘回复，录音（练英文商务表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 20, 3, 1, '数据复盘', '上架后看数据');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 20, 'am', '学习', '学习店铺数据：曝光/点击/询盘/转化', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 20, 'pm', '实战', '分析首批 10 个产品数据，找优化点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 20, 'ev', '复盘', '制定优化方案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 20, 'extra', '表达', '对着手机讲：数据告诉我什么，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 21, 3, 1, '周复盘', '上架引流启动');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 21, 'am', '学习', '回顾本周上架和引流', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 21, 'pm', '实战', '整理首批产品数据报告', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 21, 'ev', '复盘', '写周记：第一批货出海', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 21, 'extra', '表达', '录 2 分钟：上架引流心得，练''有数据地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 22, 4, 1, '直通车 P4P', '付费引流');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 22, 'am', '学习', '学习 Alibaba.com P4P 直通车原理和出价', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 22, 'pm', '实战', '给 3 个主推产品开 P4P，设日预算，观察数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 22, 'ev', '复盘', '记录 P4P 优化心得', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 22, 'extra', '表达', '口述：P4P 怎么花得值，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 23, 4, 1, '粉丝通/短视频', '内容引流');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 23, 'am', '学习', '学习 Alibaba.com 粉丝通和短视频引流', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 23, 'pm', '实战', '拍 3 条工厂/产品短视频发布', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 23, 'ev', '复盘', '记录短视频引流数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 23, 'extra', '表达', '对着镜头用英文讲产品 60 秒，录音（练英文镜头表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 24, 4, 1, '直播初探', 'B2B 也能直播');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 24, 'am', '学习', '学习 Alibaba.com 直播：工厂直播/产品展示', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 24, 'pm', '实战', '开一场 30 分钟工厂直播（可中文+英文字幕）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 24, 'ev', '复盘', '记录直播询盘数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 24, 'extra', '表达', '口述：B2B 直播怎么准备，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 25, 4, 1, '评价与信保', '建立信任');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 25, 'am', '学习', '学习信保订单和评价体系对转化的影响', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 25, 'pm', '实战', '引导首批客户走信保下单并留评价', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 25, 'ev', '复盘', '记录信保订单流程', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 25, 'extra', '表达', '对着手机讲：信保为什么重要，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 26, 4, 1, '多市场拓展', '不只一个国家');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 26, 'am', '学习', '学习多市场运营：不同国家的认证/偏好/物流', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 26, 'pm', '实战', '选定第二目标市场，针对性优化产品', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 26, 'ev', '复盘', '记录多市场差异表', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 26, 'extra', '表达', '口述：不同国家买家关注什么，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 27, 4, 1, '产品扩品', '从 10 到 30');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 27, 'am', '学习', '学习产品矩阵：引流款/利润款/形象款', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 27, 'pm', '实战', '再上架 20 个产品，形成矩阵', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 27, 'ev', '复盘', '记录产品矩阵规划', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 27, 'extra', '表达', '对着手机讲：我的产品怎么分层，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 28, 4, 1, '阶段一收尾', '基建完成');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 28, 'am', '学习', '对照阶段一目标检查', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 28, 'pm', '实战', '整理店铺全貌和数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 28, 'ev', '复盘', '写阶段一总结', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 28, 'extra', '表达', '录 3 分钟：我的店铺现状，练''有全局地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 29, 4, 1, '询盘复盘', '把询盘变订单');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 29, 'am', '学习', '分析所有询盘，找未成交原因', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 29, 'pm', '实战', '优化询盘回复策略', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 29, 'ev', '复盘', '记录询盘转化漏斗', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 29, 'extra', '表达', '口述：询盘为什么不成交，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 30, 4, 1, '缓冲日', '追赶进度');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 30, 'am', '学习', '补完落后任务', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 30, 'pm', '实战', '优化数据差的 product', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 30, 'ev', '复盘', '写月度复盘', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 30, 'extra', '表达', '录 2 分钟：第一个月出海总结，练''有沉淀地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 31, 5, 2, '询盘转化提升', '从询盘到订单');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 31, 'am', '学习', '学习 B2B 询盘转化技巧：建信任/挖需求/报价/促单/跟单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 31, 'pm', '实战', '复盘近期询盘，写转化提升方案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 31, 'ev', '复盘', '记录询盘转化 SOP', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 31, 'extra', '表达', '对着手机讲：我的促单话术，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 32, 5, 2, '报价单优化', '专业报价赢订单');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 32, 'am', '学习', '学习专业报价单结构：产品/规格/价格/条款/有效期', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 32, 'pm', '实战', '做一套英文报价单模板', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 32, 'ev', '复盘', '记录报价单 checklist', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 32, 'extra', '表达', '口述：专业报价单长什么样，录音（练英文表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 33, 5, 2, '样品单', '小单试水');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 33, 'am', '学习', '学习样品单处理：运费/质量/信任', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 33, 'pm', '实战', '处理好首批样品单，争取返单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 33, 'ev', '复盘', '记录样品单转化大单的话术', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 33, 'extra', '表达', '对着手机讲：样品单怎么变成大单，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 34, 5, 2, '谈判与让步', '谈出好价格');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 34, 'am', '学习', '学习 B2B 谈判：锚定/条件交换/让步节奏', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 34, 'pm', '实战', '模拟一场价格谈判，录音复盘', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 34, 'ev', '复盘', '记录谈判话术', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 34, 'extra', '表达', '口述：买家压价我怎么应对，录音（练谈判表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 35, 5, 2, '支付与风控', '安全收钱');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 35, 'am', '学习', '学习 B2B 支付方式：T/T/LC/信保/PayPal，及风控', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 35, 'pm', '实战', '制定支付方式策略和风控清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 35, 'ev', '复盘', '记录各支付方式优劣表', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 35, 'extra', '表达', '对着手机讲：怎么安全收款，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 36, 5, 2, '首单交付', '把第一个订单做好');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 36, 'am', '学习', '学习订单执行：产前确认/生产跟进/质检/发货', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 36, 'pm', '实战', '完成第一个正式订单的全流程', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 36, 'ev', '复盘', '记录订单执行 SOP', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 36, 'extra', '表达', '口述：一个订单从接到发要几步，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 37, 5, 2, '周复盘', '开始赚钱');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 37, 'am', '学习', '回顾本周订单转化', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 37, 'pm', '实战', '整理首单经验', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 37, 'ev', '复盘', '写周记：第一个海外订单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 37, 'extra', '表达', '录 2 分钟：首单复盘，练''有成就感地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 38, 6, 2, '客户复购', '老客户更值钱');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 38, 'am', '学习', '学习 B2B 客户复购运营：跟进/服务/新品/优惠', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 38, 'pm', '实战', '给成交客户设计复购跟进计划', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 38, 'ev', '复盘', '记录复购运营清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 38, 'extra', '表达', '对着手机讲：怎么让买家再下单，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 39, 6, 2, '客户分层', '精力花在对的人');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 39, 'am', '学习', '学习客户分层：A/B/C 客户，差异化服务', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 39, 'pm', '实战', '给所有询盘客户分层，制定跟进策略', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 39, 'ev', '复盘', '记录客户分层表', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 39, 'extra', '表达', '口述：我的客户怎么分层，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 40, 6, 2, '私域沉淀', '把平台客户变自己的');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 40, 'am', '学习', '学习 B2B 私域：WhatsApp/邮件/LinkedIn 沉淀', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 40, 'pm', '实战', '把成交/询盘客户加到 WhatsApp/邮件列表', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 40, 'ev', '复盘', '记录私域沉淀话术', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 40, 'extra', '表达', '对着手机用英文练加客户话术，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 41, 6, 2, 'EDM 营销', '主动触达老客户');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 41, 'am', '学习', '学习 EDM 邮件营销：标题/内容/频率/合规', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 41, 'pm', '实战', '给老客户发第一封新品/促销邮件', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 41, 'ev', '复盘', '记录 EDM 打开回复数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 41, 'extra', '表达', '口述：我的邮件怎么写才有人回，录音（练英文表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 42, 6, 2, '工厂背书', '让买家相信产能');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 42, 'am', '学习', '学习工厂背书展示：视频/认证/案例/验厂', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 42, 'pm', '实战', '拍一支工厂实力视频，更新到店铺', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 42, 'ev', '复盘', '记录工厂背书素材清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 42, 'extra', '表达', '对着镜头用英文介绍工厂，录音（练英文表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 43, 6, 2, '展会与线上对接', '多渠道获客');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 43, 'am', '学习', '学习线上展会和 Alibaba.com 采购对接会', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 43, 'pm', '实战', '报名参加一场线上对接会，做准备', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 43, 'ev', '复盘', '记录对接会话术', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 43, 'extra', '表达', '口述：线上对接怎么准备，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 44, 6, 2, '周复盘', '客户运营成熟');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 44, 'am', '学习', '回顾本周客户运营', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 44, 'pm', '实战', '整理客户资产表', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 44, 'ev', '复盘', '写周记：从获客到留客', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 44, 'extra', '表达', '录 2 分钟：我的客户运营法，练''有体系地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 45, 7, 2, '供应链优化', '降本增效');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 45, 'am', '学习', '学习供应链优化：采购/生产/库存/包装', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 45, 'pm', '实战', '找出成本最高的环节，优化方案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 45, 'ev', '复盘', '记录降本清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 45, 'extra', '表达', '对着手机讲：我怎么把成本降下来，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 46, 7, 2, '包装与运输', '减少破损和运费');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 46, 'am', '学习', '学习建材包装和运输优化：材积/防护/装箱', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 46, 'pm', '实战', '优化主打产品包装，降低材积重', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 46, 'ev', '复盘', '记录包装优化方案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 46, 'extra', '表达', '口述：建材怎么包才省运费，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 47, 7, 2, '售后与理赔', '把口碑守住');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 47, 'am', '学习', '学习 B2B 售后和理赔处理', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 47, 'pm', '实战', '制定售后 SOP 和理赔话术', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 47, 'ev', '复盘', '记录售后案例', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 47, 'extra', '表达', '对着手机讲：货出了问题怎么办，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 48, 7, 2, '合规与认证', '不踩出口红线');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 48, 'am', '学习', '学习建材出口认证：CE/ASTM/防火等目标国要求', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 48, 'pm', '实战', '补办缺失认证，更新到产品页', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 48, 'ev', '复盘', '记录认证清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 48, 'extra', '表达', '口述：我的货要哪些认证才能卖，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 49, 7, 2, '品牌出海', '从卖货到卖品牌');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 49, 'am', '学习', '学习 B2B 品牌出海：商标/品牌故事/视觉', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 49, 'pm', '实战', '注册海外商标，设计品牌视觉', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 49, 'ev', '复盘', '记录品牌出海清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 49, 'extra', '表达', '对着镜头讲：我的品牌故事，录音（练品牌表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 50, 7, 2, '数据复盘', '阶段二中段');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 50, 'am', '学习', '分析 20 天数据，找增长瓶颈', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 50, 'pm', '实战', '调整引流和转化策略', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 50, 'ev', '复盘', '写中段复盘', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 50, 'extra', '表达', '对着手机讲：我的增长瓶颈在哪，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 51, 7, 2, '周复盘', '引流转化成熟');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 51, 'am', '学习', '回顾阶段二，确认引流转化目标达成', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 51, 'pm', '实战', '整理阶段二方法论', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 51, 'ev', '复盘', '写周记：从上架到出单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 51, 'extra', '表达', '录 3 分钟：我的出海打法，练''有方法论地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 52, 8, 2, 'P4P 优化', '花更少的钱拿更多询盘');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 52, 'am', '学习', '学习 P4P 优化：关键词/出价/质量分/时段', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 52, 'pm', '实战', '优化 P4P 投放，记录询盘成本变化', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 52, 'ev', '复盘', '记录 P4P 优化清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 52, 'extra', '表达', '对着手机讲：我怎么让广告花得值，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 53, 8, 2, '短视频/直播常规化', '内容引流常态化');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 53, 'am', '学习', '学习内容引流常规化：固定频率/主题/数据复盘', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 53, 'pm', '实战', '每周固定 2 条短视频 + 1 场直播，连做 2 周复盘', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 53, 'ev', '复盘', '记录内容引流数据趋势', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 53, 'extra', '表达', '对着镜头用英文讲产品 60 秒，录音（练英文表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 54, 8, 2, 'RFQ 主动开发', '主动出击找买家');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 54, 'am', '学习', '学习 RFQ 高效开发：筛选/报价/跟进', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 54, 'pm', '实战', '每天报 3 条 RFQ，连续 1 周，记录回复率', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 54, 'ev', '复盘', '记录 RFQ 报价优化心得', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 54, 'extra', '表达', '口述：RFQ 怎么报价才有人回，录音（练英文表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 55, 8, 2, '客户复购运营', '老客户复购是利润源');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 55, 'am', '学习', '学习 B2B 客户复购：新品推送/节日关怀/返单优惠', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 55, 'pm', '实战', '给所有成交客户发返单激活邮件', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 55, 'ev', '复盘', '记录复购转化数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 55, 'extra', '表达', '对着手机用英文练返单激活话术，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 56, 8, 2, '多市场拓展', '第二市场起量');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 56, 'am', '学习', '学习多市场运营：认证/物流/本地化', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 56, 'pm', '实战', '选定第二市场，针对性上架 10 个产品', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 56, 'ev', '复盘', '记录第二市场数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 56, 'extra', '表达', '口述：我的第二市场为什么这么选，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 57, 8, 2, '产品扩品到 50', '丰富产品矩阵');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 57, 'am', '学习', '学习产品扩品：关联品/材质/规格/风格', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 57, 'pm', '实战', '再上架 20 个产品，总数到 50，形成矩阵', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 57, 'ev', '复盘', '记录扩品数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 57, 'extra', '表达', '对着手机讲：我的产品矩阵怎么布局，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 58, 8, 2, '周复盘', '引流深化完成');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 58, 'am', '学习', '回顾本周引流深化，盘点询盘增长', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 58, 'pm', '实战', '整理引流 SOP', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 58, 'ev', '复盘', '写周记：从被动等询盘到主动开发', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 58, 'extra', '表达', '录 2 分钟：我的主动开发法，练''有进攻性地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 59, 8, 2, '阶段二总复盘', '上架引流阶段收尾');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 59, 'am', '学习', '对照阶段二目标逐项检查', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 59, 'pm', '实战', '整理阶段二店铺/产品/客户资产', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 59, 'ev', '复盘', '写阶段二总结', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 59, 'extra', '表达', '对着镜子讲：阶段二我最大的收获，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 60, 8, 2, '缓冲日', '阶段切换休整');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 60, 'am', '学习', '补完落后任务，休整', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 60, 'pm', '实战', '准备阶段三大客户攻坚', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 60, 'ev', '复盘', '写阶段切换备忘', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 60, 'extra', '表达', '录 2 分钟：准备进入大客户攻坚，练''有信心地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 61, 9, 3, '大客户攻坚', 'B2B 的命脉');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 61, 'am', '学习', '学习大客户（工程商/连锁建材商）攻坚方法', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 61, 'pm', '实战', '列出 10 个目标大客户，做背调', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 61, 'ev', '复盘', '记录大客户攻坚清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 61, 'extra', '表达', '口述：我怎么找大客户，录音（练商务表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 62, 9, 3, '大客户触达', '让大客户注意到你');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 62, 'am', '学习', '学习大客户触达渠道：LinkedIn/邮件/展会', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 62, 'pm', '实战', '给 3 个大客户发触达邮件，跟进', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 62, 'ev', '复盘', '记录触达话术和回复率', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 62, 'extra', '表达', '对着手机用英文练大客户开发信，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 63, 9, 3, '大客户谈判', '拿下大单');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 63, 'am', '学习', '学习大客户谈判：决策链/方案/报价/样板', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 63, 'pm', '实战', '模拟大客户谈判，准备方案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 63, 'ev', '复盘', '记录大客户谈判 checklist', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 63, 'extra', '表达', '口述：大客户谈判和小客户有什么不同，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 64, 9, 3, 'OEM/ODM', '提升附加值');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 64, 'am', '学习', '学习 OEM/ODM 接单模式和利润', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 64, 'pm', '实战', '评估自己能否做 OEM，准备方案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 64, 'ev', '复盘', '记录 OEM 接单清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 64, 'extra', '表达', '对着手机讲：我能做 OEM 吗，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 65, 9, 3, '多平台拓展', '不只 Alibaba');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 65, 'am', '学习', '学习多平台：Made-in-China/Global Sources/独立站', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 65, 'pm', '实战', '评估并选 1 个新平台入驻', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 65, 'ev', '复盘', '记录多平台对比表', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 65, 'extra', '表达', '口述：我为什么选这个新平台，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 66, 9, 3, '独立站评估', '品牌资产');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 66, 'am', '学习', '学习 B2B 独立站价值和建站方式', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 66, 'pm', '实战', '评估建独立站的成本收益，决定是否启动', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 66, 'ev', '复盘', '记录独立站方案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 66, 'extra', '表达', '对着手机讲：我要不要建独立站，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 67, 9, 3, '周复盘', '大客户攻坚启动');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 67, 'am', '学习', '回顾本周大客户动作', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 67, 'pm', '实战', '整理大客户管道', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 67, 'ev', '复盘', '写周记：从零售到批发到工程', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 67, 'extra', '表达', '录 2 分钟：我的大客户策略，练''有格局地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 68, 10, 3, '团队化评估', '从一个人到小团队');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 68, 'am', '学习', '学习跨境电商团队化：运营/业务/跟单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 68, 'pm', '实战', '评估自己哪些环节需要人手', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 68, 'ev', '复盘', '记录可招/外包的岗位', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 68, 'extra', '表达', '口述：我什么时候该招人，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 69, 10, 3, '财务与税务', '把账算清');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 69, 'am', '学习', '学习跨境电商财务：成本/利润/退税/税务', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 69, 'pm', '实战', '梳理财务流程，建简单账本', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 69, 'ev', '复盘', '记录财务 checklist', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 69, 'extra', '表达', '对着手机讲：我的利润到底怎么算，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 70, 10, 3, '风险管控', '可持续出海');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 70, 'am', '学习', '学习跨境电商风险：汇率/库存/平台政策/客户违约', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 70, 'pm', '实战', '制定风险预案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 70, 'ev', '复盘', '记录风险清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 70, 'extra', '表达', '口述：出海最大的风险是什么，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 71, 10, 3, '数据复盘', '90 天中段');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 71, 'am', '学习', '分析全部订单和客户数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 71, 'pm', '实战', '对照阶段三目标找差距', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 71, 'ev', '复盘', '写中段复盘', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 71, 'extra', '表达', '对着手机讲：我的出海成绩单，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 72, 10, 3, '客户案例化', '用案例获客');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 72, 'am', '学习', '学习用成功案例做背书获客', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 72, 'pm', '实战', '把首单/大单整理成英文案例', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 72, 'ev', '复盘', '记录案例库', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 72, 'extra', '表达', '对着镜头用英文讲客户案例，录音（练英文表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 73, 10, 3, '内容营销', 'B2B 也做内容');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 73, 'am', '学习', '学习 B2B 内容营销：LinkedIn/YouTube 工厂内容', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 73, 'pm', '实战', '发 3 条 LinkedIn 内容，建专业形象', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 73, 'ev', '复盘', '记录内容引流数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 73, 'extra', '表达', '口述：B2B 内容怎么写，录音（练英文表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 74, 10, 3, '周复盘', '规模化准备');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 74, 'am', '学习', '回顾本周规模化准备', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 74, 'pm', '实战', '整理规模化 checklist', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 74, 'ev', '复盘', '写周记：从能卖到能复制', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 74, 'extra', '表达', '录 2 分钟：我的规模化计划，练''有远见地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 75, 11, 3, '年度规划', '把出海当事业');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 75, 'am', '学习', '学习跨境电商年度规划：GMV/市场/产品/团队目标', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 75, 'pm', '实战', '写下一年出海规划', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 75, 'ev', '复盘', '记录关键里程碑', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 75, 'extra', '表达', '对着镜子讲：1 年后我的出海生意什么样，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 76, 11, 3, '供应链深耕', '护城河');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 76, 'am', '学习', '学习供应链深耕：独家货源/定制/成本优势', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 76, 'pm', '实战', '和上游谈独家或定制合作', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 76, 'ev', '复盘', '记录供应链优势清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 76, 'extra', '表达', '口述：我的供应链护城河是什么，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 77, 11, 3, '品牌资产', '长期主义');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 77, 'am', '学习', '学习品牌资产积累：商标/口碑/案例/内容', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 77, 'pm', '实战', '盘点并补齐品牌资产', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 77, 'ev', '复盘', '记录品牌资产清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 77, 'extra', '表达', '对着手机讲：我的品牌值多少，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 78, 11, 3, '跨境合规升级', '走得远');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 78, 'am', '学习', '学习跨境合规升级：税务/数据/产品/贸易', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 78, 'pm', '实战', '排查合规风险，制定升级方案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 78, 'ev', '复盘', '记录合规清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 78, 'extra', '表达', '口述：怎么合规地做大，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 79, 11, 3, '数据复盘', '阶段三中段');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 79, 'am', '学习', '分析近 20 天大客户/规模数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 79, 'pm', '实战', '调整策略', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 79, 'ev', '复盘', '写中段复盘', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 79, 'extra', '表达', '对着手机讲：我的规模化进展，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 80, 11, 3, '周复盘', '事业化推进');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 80, 'am', '学习', '回顾本周事业化动作', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 80, 'pm', '实战', '整理出海事业资产', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 80, 'ev', '复盘', '写周记：从卖货到事业', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 80, 'extra', '表达', '录 2 分钟：我的出海事业蓝图，练''有愿景地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 81, 11, 3, '表达终极训练', '跨境商务表达');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 81, 'am', '学习', '回顾 90 天英文商务表达，归纳进步', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 81, 'pm', '实战', '做一次全英文即兴产品介绍训练', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 81, 'ev', '复盘', '整理''我的英文表达进化史''', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 81, 'extra', '表达', '录 3 分钟：全英文讲我的生意，练''有自信地英文表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 82, 12, 3, '与自媒体联动', '内容带跨境');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 82, 'am', '学习', '学习自媒体内容带跨境的玩法', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 82, 'pm', '实战', '规划自媒体内容如何给跨境电商引流（如小红书讲建材知识）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 82, 'ev', '复盘', '记录联动方案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 82, 'extra', '表达', '对着手机讲：内容怎么帮我卖货，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 83, 12, 3, '与 AI 联动', '技术带跨境');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 83, 'am', '学习', '学习 AI 工具提效跨境运营（翻译/选品/客服）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 83, 'pm', '实战', '把 AI 工具应用到日常跨境运营', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 83, 'ev', '复盘', '记录 AI 提效清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 83, 'extra', '表达', '口述：AI 怎么帮我做出海，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 84, 12, 3, '90 天总复盘', '完整回顾');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 84, 'am', '学习', '对照 90 天目标逐项检查', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 84, 'pm', '实战', '整理 90 天订单/客户/收入总表', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 84, 'ev', '复盘', '写''90 天建材出海复盘''长文', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 84, 'extra', '表达', '录 3 分钟：我的 90 天出海之路，练''有总结力地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 85, 12, 3, '客户答谢', '长期合作');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 85, 'am', '学习', '学习客户答谢和长期关系维护', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 85, 'pm', '实战', '给成交客户发感谢信/小礼品', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 85, 'ev', '复盘', '记录客户反馈', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 85, 'extra', '表达', '对着镜头用英文讲：感谢信任，练''有温度地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 86, 12, 3, '利润优化', '赚得更多');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 86, 'am', '学习', '分析各环节利润，找优化空间', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 86, 'pm', '实战', '砍掉低利润产品/客户，加码高利润', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 86, 'ev', '复盘', '记录利润优化方案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 86, 'extra', '表达', '口述：我怎么赚得更多，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 87, 12, 3, '经验输出', '帮同行少走弯路');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 87, 'am', '学习', '把 90 天经验整理成''建材 B2B 出海指南''', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 87, 'pm', '实战', '发布到自媒体/行业群', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 87, 'ev', '复盘', '记录传播反馈', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 87, 'extra', '表达', '对着手机讲：给出海新手的 3 条建议，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 88, 12, 3, '缓冲日', '处理未尽事宜');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 88, 'am', '学习', '补完落后任务', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 88, 'pm', '实战', '处理商务收尾', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 88, 'ev', '复盘', '整理文件', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 88, 'extra', '表达', '口述：我现在的心态，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 89, 12, 3, '下一程规划', '三线协同');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 89, 'am', '学习', '思考跨境电商与 AI/自媒体的深度协同', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 89, 'pm', '实战', '写三线协同 1 年计划', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 89, 'ev', '复盘', '记录协同点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 89, 'extra', '表达', '对着镜子讲：我的三线作战怎么协同，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (4, 90, 12, 3, '90 天毕业', '毕业总结');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 90, 'am', '学习', '回顾整个打卡系统，导出存档', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 90, 'pm', '实战', '完成毕业总结', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 90, 'ev', '复盘', '发毕业动态', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (4, 90, 'extra', '表达', '录 3 分钟毕业感言：给 90 天前的自己，练''有力量地表达''', 0);
