INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 1, 1, 1, 'Python 速成：从 JS 到 Python', '能读能写 Python 基础脚本');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 1, 'am', '理论', '对比学习：Python 与 JS 的变量/数据类型/函数差异（看廖雪峰 Python 教程前 5 节）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 1, 'pm', '实战', '装好 Python 3.12 + venv + VS Code，写一个爬取天气的 .py 脚本跑通', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 1, 'ev', '复盘', '整理 JS→Python 语法对照表存入笔记（dict=对象 list=数组 def=function）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 1, 'extra', '素材', '录一段 60 秒语音：用大白话讲''我为什么要学 Python''（练表达，存手机不发）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 2, 1, 1, 'Python 进阶：列表推导 + 装饰器', '能看懂第三方库源码里的 Python 惯用法');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 2, 'am', '理论', '学列表推导式、字典推导式、*args/**kwargs、装饰器基础', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 2, 'pm', '实战', '用 requests 库调一个免费 API（如心知天气），打印 JSON 结果', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 2, 'ev', '复盘', '把今天踩的坑（缩进/编码/venv 激活）写成 3 条避坑笔记', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 2, 'extra', '素材', '口述复述：什么是装饰器？对着镜子讲一遍，录音回听', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 3, 1, 1, 'HTTP 与 JSON：前后端通吃的视角', '理解 API 请求/响应全链路');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 3, 'am', '理论', '复习 HTTP 方法/状态码/Header，对比 fetch 与 requests 的用法', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 3, 'pm', '实战', '用 Python 写一个极简 Flask 服务返回 JSON，再用 Vue 调它', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 3, 'ev', '复盘', '画一张请求生命周期图（浏览器→DNS→服务器→响应）存笔记', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 3, 'extra', '素材', '发一条小红书/朋友圈：今天学会的 1 个 Python 知识点（练公开表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 4, 1, 1, '环境管理：venv 与 pip', '能隔离项目依赖，不污染系统');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 4, 'am', '理论', '理解 venv/pip/requirements.txt 的作用，对比 npm', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 4, 'pm', '实战', '给天气脚本建独立 venv，导出 requirements.txt，换目录重装跑通', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 4, 'ev', '复盘', '整理 Python 环境管理速查表（创建/激活/导出/安装镜像源）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 4, 'extra', '素材', '用 3 句话向空气解释''为什么要用虚拟环境''，录音计时≤30 秒', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 5, 1, 1, 'LLM 是什么：Token 与上下文', '理解大模型的基本概念与计费');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 5, 'am', '理论', '看视频：LLM 工作原理（Token/采样/temperature/上下文窗口）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 5, 'pm', '实战', '注册 OpenAI 或国内平台（DeepSeek/通义/智谱），用 curl 调通第一次 chat', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 5, 'ev', '复盘', '记录 Token 计费规则，算一下 1 元能买多少 Token', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 5, 'extra', '素材', '把''什么是 Token''写成一条朋友圈文案，要求通俗易懂', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 6, 1, 1, 'Prompt 工程基础', '能写出结构化 System Prompt');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 6, 'am', '理论', '学习 Prompt 结构：角色+任务+约束+输出格式，看 OpenAI 官方 Prompt 指南', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 6, 'pm', '实战', '写一个''翻译助手''Prompt，让模型稳定输出指定语言，测 10 次看稳定性', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 6, 'ev', '复盘', '整理 Prompt 模板库（翻译/总结/改写/提取），存 Notion/Obsidian', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 6, 'extra', '素材', '对着手机录音：讲解''好的 Prompt 有哪几个要素''，目标 1 分钟讲清', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 7, 1, 1, '周复盘 + 第 2 周预习', '第一周笔记 + Demo 整理');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 7, 'am', '理论', '回顾本周 Python+LLM 笔记，查漏补缺，标记不懂的点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 7, 'pm', '实战', '把天气脚本+翻译助手整理到 GitHub 仓库，写 README', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 7, 'ev', '复盘', '写周记：本周学了什么/卡在哪/下周计划，发知识星球或备忘录', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 7, 'extra', '素材', '录一段 2 分钟周复盘语音，刻意练习''有条理地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 8, 2, 1, 'LLM API 深入：多轮对话', '实现带上下文的多轮对话');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 8, 'am', '理论', '读 API 文档：messages 数组、role(system/user/assistant)、上下文截断', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 8, 'pm', '实战', '用 Python 写一个命令行多轮对话程序，保留最近 10 轮上下文', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 8, 'ev', '复盘', '画图：多轮对话的 messages 如何累积，存笔记', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 8, 'extra', '素材', '口述：为什么要截断上下文？录音≤45 秒', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 9, 2, 1, '流式输出：SSE 原理', '打通模型流式管道');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 9, 'am', '理论', '学习 SSE 协议，对比 WebSocket，看 EventSource API', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 9, 'pm', '实战', '用 Python 实现 SSE 服务，前端 Vue 用 EventSource 接收逐字输出', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 9, 'ev', '复盘', '记录流式 vs 非流式的体验差异和实现要点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 9, 'extra', '素材', '发一条技术动态：今天搞懂了 SSE（练公开表达，哪怕只有几个赞）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 10, 2, 1, 'Function Calling：让模型调工具', '跑通第一个工具调用');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 10, 'am', '理论', '学习 Function Calling 原理：模型如何决定调用哪个函数', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 10, 'pm', '实战', '实现''天气查询''工具：模型识别用户意图→调天气 API→返回自然语言回答', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 10, 'ev', '复盘', '整理 Function Calling 的请求/响应 JSON 结构到笔记', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 10, 'extra', '素材', '对着镜子讲解 Function Calling 流程，录音回听找卡顿点', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 11, 2, 1, '结构化输出：JSON Mode', '让模型稳定输出可解析 JSON');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 11, 'am', '理论', '学习 JSON Mode / response_format，理解模型输出的不确定性', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 11, 'pm', '实战', '写一个''信息提取''程序：从一段新闻里提取人物/时间/地点为 JSON', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 11, 'ev', '复盘', '记录让模型稳定输出 JSON 的 3 个技巧（示例/约束/校验重试）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 11, 'extra', '素材', '用大白话写一条朋友圈：什么是结构化输出，为什么重要', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 12, 2, 1, '错误处理与重试', '构建稳定的 LLM 调用封装');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 12, 'am', '理论', '学习 API 限流/超时/错误码，理解指数退避重试', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 12, 'pm', '实战', '封装一个 call_llm() 函数：自动重试+超时+错误日志', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 12, 'ev', '复盘', '整理 LLM 应用常见错误清单及应对策略', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 12, 'extra', '素材', '口述：我的 LLM 封装解决了什么问题，录音≤1 分钟', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 13, 2, 1, '模型选型与成本', '能根据任务选对模型控成本');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 13, 'am', '理论', '对比 GPT-4o/Claude/DeepSeek/通义 的能力与价格，看 LMSYS 排行榜', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 13, 'pm', '实战', '用同一组 Prompt 测 3 个模型，记录效果与成本差异', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 13, 'ev', '复盘', '制作''模型选型决策表''（任务→推荐模型→单价→质量分）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 13, 'extra', '素材', '录一段：如果我给公司选模型会怎么选，练习有逻辑地表达观点', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 14, 2, 1, '周复盘 + 小作品集成', '作品 1 骨架：AI 对话 CLI');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 14, 'am', '理论', '回顾本周 API 学习，整理知识清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 14, 'pm', '实战', '把多轮对话+流式+工具调用整合成一个命令行 AI 助手 v0.1', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 14, 'ev', '复盘', '写周记发到掘金或公众号草稿箱（练公开输出，不必求完美）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 14, 'extra', '素材', '录 2 分钟视频：演示我的 AI 助手，练习边操作边讲解', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 15, 3, 1, 'Embedding 与向量', '理解向量检索原理');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 15, 'am', '理论', '学习词向量/句向量概念，理解余弦相似度，看 OpenAI Embedding 文档', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 15, 'pm', '实战', '用 Embedding API 把 10 句话转向量，计算两两相似度排序', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 15, 'ev', '复盘', '画图：文本→向量→相似度计算的可视化，存笔记', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 15, 'extra', '素材', '口述：什么是向量相似度？为什么能做语义搜索，录音≤1 分钟', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 16, 3, 1, '向量库入门：Chroma', '向量入库 + 检索');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 16, 'am', '理论', '学习 Chroma/Qdrant 等向量库概念，对比传统数据库', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 16, 'pm', '实战', '本地装 Chroma，把 20 段文本入库，实现 top-k 相似检索', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 16, 'ev', '复盘', '整理向量库 CRUD 速查表', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 16, 'extra', '素材', '发一条动态：向量库和 MySQL 有什么不同（练技术表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 17, 3, 1, '文本处理：切片与清洗', '文档→切片管道');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 17, 'am', '理论', '学习文本切片策略：固定长度/重叠/按句子/递归切片', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 17, 'pm', '实战', '写一个 PDF→文本→切片的管道，对比不同切片长度对检索的影响', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 17, 'ev', '复盘', '记录切片参数调优心得', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 17, 'extra', '素材', '对着手机讲：为什么要切片，切多大合适，录音回听', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 18, 3, 1, '最小 RAG 问答', '能回答文档里的问题');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 18, 'am', '理论', '理解 RAG 全流程：文档→切片→Embedding→入库→检索→拼 Prompt→生成', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 18, 'pm', '实战', '实现一个最小 RAG：上传一份 PDF，问问题，模型基于文档回答', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 18, 'ev', '复盘', '画 RAG 架构图存笔记', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 18, 'extra', '素材', '录一段 90 秒：用大白话讲 RAG 是干什么的', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 19, 3, 1, 'RAG 进阶：引用溯源', '回答带来源');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 19, 'am', '理论', '学习如何把检索片段的来源（页码/段落）带入回答', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 19, 'pm', '实战', '给 RAG 加引用标注：回答后附''来源：第 X 页''', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 19, 'ev', '复盘', '整理引用溯源的实现要点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 19, 'extra', '素材', '写一条技术朋友圈：RAG 不是万能的，但它解决了什么问题', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 20, 3, 1, '检索质量优化', '召回率提升');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 20, 'am', '理论', '学习混合检索（关键词+向量）、Rerank 重排', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 20, 'pm', '实战', '给 RAG 加 Rerank，对比重排前后答案准确度', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 20, 'ev', '复盘', '记录检索质量评估方法（召回率/准确率主观打分）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 20, 'extra', '素材', '口述：向量检索为什么不够，还要 Rerank，录音≤45 秒', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 21, 3, 1, '周复盘 + RAG 小结', 'RAG 基础笔记完整');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 21, 'am', '理论', '回顾本周 RAG 内容，整理成一篇结构化笔记', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 21, 'pm', '实战', '把 RAG Demo 整理到 GitHub，补 README 和截图', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 21, 'ev', '复盘', '把笔记发到掘金/知乎草稿（练长文表达，不求一次发）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 21, 'extra', '素材', '录 2 分钟：这周做的 RAG 项目，练习有条理地讲技术', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 22, 4, 1, 'Agent 概念：ReAct 模式', '手写 ReAct 循环');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 22, 'am', '理论', '学习 Agent 概念：感知→思考→行动，ReAct（推理+行动）模式', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 22, 'pm', '实战', '手写一个最小 ReAct 循环：模型决定调用工具→执行→观察→再思考', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 22, 'ev', '复盘', '画 ReAct 循环流程图存笔记', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 22, 'extra', '素材', '对着镜子讲：Agent 和普通 LLM 调用有什么区别，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 23, 4, 1, 'Agent 工具集成', '天气+计算+搜索 3 个工具');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 23, 'am', '理论', '学习如何定义工具的 schema（名称/描述/参数）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 23, 'pm', '实战', '给 Agent 加 3 个工具：天气查询、数学计算、网络搜索', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 23, 'ev', '复盘', '整理工具定义模板', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 23, 'extra', '素材', '发动态：今天让 AI 学会了用 3 个工具（练公开表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 24, 4, 1, 'Agent 记忆', '短期 + 长期记忆');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 24, 'am', '理论', '学习 Agent 记忆机制：对话窗口/摘要记忆/向量长期记忆', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 24, 'pm', '实战', '给 Agent 加长期记忆：把关键信息存向量库，下次检索召回', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 24, 'ev', '复盘', '记录 3 种记忆的适用场景', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 24, 'extra', '素材', '口述：AI 怎么记住你，录音≤1 分钟', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 25, 4, 1, 'LangChain/LlamaIndex 入门', '用框架重构 Agent');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 25, 'am', '理论', '对比 LangChain 与 LlamaIndex，选一个深入', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 25, 'pm', '实战', '用 LangChain 重写之前的 Agent，对比手写版的差异', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 25, 'ev', '复盘', '整理框架核心概念速查（Chain/Agent/Memory/Tool）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 25, 'extra', '素材', '写一条朋友圈：框架 vs 手写，我的选择和理由（练观点表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 26, 4, 1, '多 Agent 协作', '两 Agent 协作 Demo');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 26, 'am', '理论', '学习多 Agent 协作模式（CrewAI/AutoGen 概念）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 26, 'pm', '实战', '实现一个''写作 Agent + 审校 Agent''协作：一个写一个改', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 26, 'ev', '复盘', '记录多 Agent 通信的几种模式', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 26, 'extra', '素材', '对着手机讲：多个 AI 怎么分工合作，录音回听', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 27, 4, 1, '作品 1 集成：AI 知识库助手', '端到端可用');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 27, 'am', '理论', '回顾阶段一所有模块，规划整合方案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 27, 'pm', '实战', '把 RAG + Agent + 前端整合成''个人知识库助手''v1.0', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 27, 'ev', '复盘', '写作品 1 的功能清单和技术架构文档', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 27, 'extra', '素材', '录 3 分钟视频：演示并讲解我的 AI 知识库助手（练项目讲解）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 28, 4, 1, '前端集成：Vue + AI 对话组件', '高保真聊天界面');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 28, 'am', '理论', '复习 Vue3 + TS，规划 AI 对话 UI 组件结构', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 28, 'pm', '实战', '用 Vue 实现流式对话组件：消息列表+输入框+Markdown 渲染+代码高亮', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 28, 'ev', '复盘', '记录前端集成 AI 的 3 个坑（SSE/类型/状态）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 28, 'extra', '素材', '口述：前端接 AI 接口和接普通接口有什么不同，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 29, 4, 1, '阶段一收尾：查漏补缺', '阶段一知识清单 100%');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 29, 'am', '理论', '对照阶段一目标逐项检查，标记薄弱点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 29, 'pm', '实战', '补练薄弱环节，更新知识库助手代码', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 29, 'ev', '复盘', '把阶段一笔记整理成一篇''前端转 AI 30 天''长文存草稿', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 29, 'extra', '素材', '对着镜子完整讲一遍作品 1，计时 3 分钟，录音找卡顿', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 30, 4, 1, '缓冲日 + 阶段小结', '追赶进度 + 阶段复盘');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 30, 'am', '理论', '补完落后任务，或深化某个感兴趣的方向', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 30, 'pm', '实战', '整理阶段一全部代码到 GitHub，打 tag v0.1', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 30, 'ev', '复盘', '写阶段一复盘：学到了什么/最大的坑/下阶段重点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 30, 'extra', '素材', '录 2 分钟阶段复盘语音，刻意练''有开头有结尾地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 31, 5, 2, 'RAG 进阶：查询改写', '复杂问题召回提升');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 31, 'am', '理论', '学习查询改写/HyDE（假设性文档嵌入）技术', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 31, 'pm', '实战', '给知识库助手加查询改写，对比改写前后召回效果', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 31, 'ev', '复盘', '记录查询改写的适用场景', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 31, 'extra', '素材', '发动态：一个技巧让 AI 搜索更准（练技术传播）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 32, 5, 2, '多文档知识库', '支持多来源问答');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 32, 'am', '理论', '学习多文档管理：来源标识/合并检索/冲突处理', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 32, 'pm', '实战', '让助手支持上传多个 PDF，跨文档问答', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 32, 'ev', '复盘', '整理多文档 RAG 的数据结构设计', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 32, 'extra', '素材', '口述：多个文档答案冲突怎么办，录音≤1 分钟', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 33, 5, 2, '幻觉抑制', '无据不答');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 33, 'am', '理论', '学习幻觉成因与抑制策略：置信度/引用校验/拒答', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 33, 'pm', '实战', '给助手加''无依据则拒答''逻辑，测试边界问题', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 33, 'ev', '复盘', '记录幻觉抑制的 3 个工程手段', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 33, 'extra', '素材', '对着手机讲：AI 为什么会胡说，怎么治，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 34, 5, 2, 'Agent 实战：自动调研', '让 Agent 自主搜集信息');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 34, 'am', '理论', '学习规划型 Agent：拆任务→搜索→汇总→输出报告', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 34, 'pm', '实战', '实现一个''主题调研 Agent''：输入主题，自动搜 5 篇资料出摘要', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 34, 'ev', '复盘', '画 Agent 任务规划流程图', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 34, 'extra', '素材', '写一条朋友圈：我让 AI 替我做了次调研（练成果展示表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 35, 5, 2, 'Agent 工作流：Dify/Coze', '低代码搭工作流');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 35, 'am', '理论', '体验 Dify 或 Coze，对比手写代码的差异', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 35, 'pm', '实战', '用 Dify 搭一个''客服机器人''工作流并发布', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 35, 'ev', '复盘', '整理低代码 vs 代码的取舍（效率 vs 灵活）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 35, 'extra', '素材', '口述：什么场景该用 Dify 什么场景该手写，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 36, 5, 2, '多模态：图片理解', '接入视觉模型');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 36, 'am', '理论', '学习多模态模型（GPT-4o/Claude 视觉），理解图片输入', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 36, 'pm', '实战', '给助手加''上传图片问问题''功能', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 36, 'ev', '复盘', '记录多模态 API 的请求结构', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 36, 'extra', '素材', '发动态：AI 看图说话实战（练公开表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 37, 5, 2, '周复盘 + 作品 2 规划', 'RAG/Agent 进阶笔记全');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 37, 'am', '理论', '回顾本周进阶内容，整理知识地图', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 37, 'pm', '实战', '规划作品 2：一个面向真实场景的 AI 应用', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 37, 'ev', '复盘', '写周记，尝试发一篇短文到掘金', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 37, 'extra', '素材', '录 2 分钟：本周最有成就感的一件事（练积极表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 38, 6, 2, '作品 2 立项', '确定方向 + 需求文档');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 38, 'am', '理论', '调研 3 个 AI 应用方向（如 AI 简历优化/AI 周报/AI 客服），选一个', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 38, 'pm', '实战', '写作品 2 需求文档：用户是谁/解决什么/核心功能/MVP 范围', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 38, 'ev', '复盘', '画产品原型草图（纸笔或 Figma）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 38, 'extra', '素材', '对着手机讲 2 分钟：我的产品解决什么问题（练产品表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 39, 6, 2, '作品 2 后端：API 设计', '定义接口 + 数据模型');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 39, 'am', '理论', '设计后端 API（RESTful）：端点/请求/响应/错误码', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 39, 'pm', '实战', '用 FastAPI/Flask 搭后端骨架，写好 3 个核心接口', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 39, 'ev', '复盘', '整理 API 文档（可用 Apifox/Postman）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 39, 'extra', '素材', '口述：我的 API 怎么设计的，为什么这么分，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 40, 6, 2, '作品 2 核心功能 1', '打通主链路');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 40, 'am', '理论', '规划核心功能开发顺序（先跑通再优化）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 40, 'pm', '实战', '实现核心功能 1：前端+后端+LLM 串通，能跑', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 40, 'ev', '复盘', '记录开发中遇到的技术决策及理由', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 40, 'extra', '素材', '发动态：作品 2 主链路跑通了（练里程碑表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 41, 6, 2, '作品 2 核心功能 2', '补齐关键能力');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 41, 'am', '理论', '规划第二个核心功能，评估复用已有模块', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 41, 'pm', '实战', '实现核心功能 2，保持代码可维护', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 41, 'ev', '复盘', '重构：把重复逻辑抽成公共模块', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 41, 'extra', '素材', '对着镜子讲：我的代码架构长什么样，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 42, 6, 2, '作品 2 前端打磨', '交互细节 + 体验');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 42, 'am', '理论', '复习前端体验设计原则（反馈/一致性/容错）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 42, 'pm', '实战', '打磨前端：加载态/错误提示/空状态/流式动画', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 42, 'ev', '复盘', '记录前端体验优化的 5 个细节', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 42, 'extra', '素材', '口述：好用的 AI 应用 UI 长啥样，录音≤1 分钟', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 43, 6, 2, '作品 2 联调 + 修 bug', '端到端稳定');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 43, 'am', '理论', '制定联调 checklist（功能/边界/异常）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 43, 'pm', '实战', '按 checklist 自测，修复发现的问题', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 43, 'ev', '复盘', '整理 bug 清单和修复方案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 43, 'extra', '素材', '写一条朋友圈：联调踩坑记（练技术故事表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 44, 6, 2, '周复盘 + 作品 2 联调', '作品 2 端到端可用');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 44, 'am', '理论', '回顾本周开发，整理技术债务清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 44, 'pm', '实战', '作品 2 完成 MVP，录演示视频存本地', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 44, 'ev', '复盘', '写周记，把作品 2 介绍写成一篇短文存草稿', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 44, 'extra', '素材', '录 3 分钟：完整演示并讲解作品 2（练项目讲解，反复录到顺）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 45, 7, 2, '部署基础：Linux + Docker', '能容器化部署');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 45, 'am', '理论', '学习 Docker 基础：镜像/容器/Dockerfile/端口映射', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 45, 'pm', '实战', '给作品 2 写 Dockerfile，本地 docker run 跑通', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 45, 'ev', '复盘', '整理 Docker 常用命令速查', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 45, 'extra', '素材', '口述：为什么要用 Docker 部署，录音≤45 秒', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 46, 7, 2, '云端部署', '上线可访问');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 46, 'am', '理论', '学习云服务器基础（阿里云/腾讯云轻量），了解域名/备案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 46, 'pm', '实战', '把作品 2 部署到云服务器，公网可访问', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 46, 'ev', '复盘', '记录部署 checklist（环境/端口/Nginx/HTTPS）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 46, 'extra', '素材', '发动态：我的 AI 应用上线了（附链接，练成果公开表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 47, 7, 2, '可观测性：日志 + 监控', '能排查线上问题');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 47, 'am', '理论', '学习日志规范（结构化/级别/轮转）和基础监控', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 47, 'pm', '实战', '给作品 2 加日志和简单监控（如访问计数/错误率）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 47, 'ev', '复盘', '整理''线上出问题怎么排查''的 SOP', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 47, 'extra', '素材', '对着手机讲：线上挂了我会怎么查，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 48, 7, 2, '性能优化', '响应更快成本更低');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 48, 'am', '理论', '学习 LLM 应用的性能瓶颈：首 Token 延迟/并发/缓存', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 48, 'pm', '实战', '给作品 2 加缓存 + 流式首字优化，测量改进', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 48, 'ev', '复盘', '记录性能优化的 3 个杠杆', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 48, 'extra', '素材', '口述：AI 应用慢在哪里怎么优化，录音≤1 分钟', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 49, 7, 2, '安全与合规', '不踩数据/隐私红线');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 49, 'am', '理论', '学习 Prompt 注入/API 鉴权/数据脱敏/内容审核', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 49, 'pm', '实战', '给作品 2 加鉴权 + 敏感词过滤', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 49, 'ev', '复盘', '整理 AI 应用安全 checklist', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 49, 'extra', '素材', '写一条朋友圈：AI 应用的 3 个安全坑（练风险表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 50, 7, 2, '作品 2 收尾 + 文档', '完整项目文档');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 50, 'am', '理论', '回顾作品 2，补齐缺失功能', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 50, 'pm', '实战', '写完整 README：功能/架构/部署/截图/演示链接', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 50, 'ev', '复盘', '把项目笔记整理成一篇''我是怎么做 XX 的''长文发草稿', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 50, 'extra', '素材', '录 3 分钟作品 2 最终版讲解视频，练到流畅', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 51, 7, 2, '周复盘 + 求职准备启动', '作品 2 完成 + 求职清单');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 51, 'am', '理论', '回顾本周，确认作品 2 达到可展示状态', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 51, 'pm', '实战', '列出目标岗位 JD（AI 应用/全栈/AI 工程师）10 条，提炼共性要求', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 51, 'ev', '复盘', '写周记，对照 JD 找出自己的差距', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 51, 'extra', '素材', '对着镜子讲：我的两个作品分别能证明什么能力，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 52, 8, 2, '技术博客选题 + 大纲', '开始公开输出建立影响力');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 52, 'am', '理论', '学习技术博客选题：从踩坑/对比/实战/源码角度找切入点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 52, 'pm', '实战', '选 1 个作品相关选题，写博客大纲（问题-方案-实现-反思）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 52, 'ev', '复盘', '记录选题判断标准', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 52, 'extra', '素材', '口述：我的博客要写给谁看解决什么，录音（练受众表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 53, 8, 2, '技术博客写作 + 发布', '第一篇公开长文');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 53, 'am', '理论', '学习技术长文写作：结构/配图/代码/可读性', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 53, 'pm', '实战', '完成第一篇博客并发布到掘金/知乎', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 53, 'ev', '复盘', '记录写作耗时和发布数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 53, 'extra', '素材', '发动态：我的第一篇 AI 技术博客（练成果公开表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 54, 8, 2, 'GitHub Profile 打磨', '让代码会说话');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 54, 'am', '理论', '学习 GitHub Profile 打造：README/Pin/贡献图', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 54, 'pm', '实战', '写 GitHub Profile README，Pin 两个 AI 作品，补项目 README', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 54, 'ev', '复盘', '记录 GitHub 打磨 checklist', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 54, 'extra', '素材', '对着手机讲：招聘方看我的 GitHub 会看到什么，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 55, 8, 2, '开源贡献尝试', '参与社区提升背书');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 55, 'am', '理论', '学习参与开源流程：找项目/读源码/提 issue/提 PR', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 55, 'pm', '实战', '找一个 AI 相关开源项目，提一个 issue 或小 PR', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 55, 'ev', '复盘', '记录开源参与心得', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 55, 'extra', '素材', '口述：参与开源对求职有什么帮助，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 56, 8, 2, '技术社区参与', '在圈子建立存在感');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 56, 'am', '理论', '学习技术社区运营：掘金/知乎/即刻，回答问题建信任', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 56, 'pm', '实战', '在知乎/掘金回答 3 个 AI 相关问题', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 56, 'ev', '复盘', '记录社区互动数据', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 56, 'extra', '素材', '对着手机讲：我怎么在社区建立专业形象，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 57, 8, 2, '知识体系梳理', '把零散变体系');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 57, 'am', '理论', '学习知识体系化：用思维导图/笔记串联 60 天所学', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 57, 'pm', '实战', '画一张''AI 应用工程师能力地图''，标记已掌握/待加强', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 57, 'ev', '复盘', '记录能力地图存档', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 57, 'extra', '素材', '口述：我的 AI 能力地图长什么样，录音（练体系化表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 58, 8, 2, '周复盘', '技术影响力起步');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 58, 'am', '理论', '回顾本周影响力建设，盘点产出', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 58, 'pm', '实战', '整理本周博客/社区/GitHub 成果', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 58, 'ev', '复盘', '写周记：从做项目到建影响力', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 58, 'extra', '素材', '录 2 分钟：我的技术影响力起步，练''有沉淀地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 59, 8, 2, '阶段二总复盘', 'RAG+Agent 实战完成');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 59, 'am', '理论', '对照阶段二目标逐项检查', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 59, 'pm', '实战', '整理阶段二全部作品/代码/文档到 GitHub 打 tag v0.2', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 59, 'ev', '复盘', '写阶段二总结：从 RAG 到 Agent 到上线', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 59, 'extra', '素材', '对着镜子讲：阶段二我最大的成长，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 60, 8, 2, '缓冲日', '阶段切换休整');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 60, 'am', '理论', '补完落后任务，或深化感兴趣方向', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 60, 'pm', '实战', '休整 + 准备阶段三求职物料', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 60, 'ev', '复盘', '写阶段切换备忘', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 60, 'extra', '素材', '录 2 分钟：准备进入求职冲刺，练''有信心地表达''', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 61, 9, 3, '简历重构：AI 方向', '简历突出 AI 能力');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 61, 'am', '理论', '研究 AI 岗位简历写法：项目要写清技术栈+量化成果', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 61, 'pm', '实战', '重写简历：把 2 个 AI 作品写成 STAR 结构（情境-任务-行动-结果）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 61, 'ev', '复盘', '整理简历自查清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 61, 'extra', '素材', '口述：用 1 分钟讲我的核心项目，录音找冗余', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 62, 9, 3, '作品讲解稿', '能流利讲清作品');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 62, 'am', '理论', '为每个作品写 2 分钟讲解稿（问题-方案-技术-成果）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 62, 'pm', '实战', '对照讲解稿口练 5 遍，录音回听修正卡顿', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 62, 'ev', '复盘', '整理''被追问时的应答预案''（架构选型/难点/优化）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 62, 'extra', '素材', '找朋友/家人模拟听你讲作品，收集反馈（练真实表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 63, 9, 3, '面试基础：Python + LLM', '高频题能答');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 63, 'am', '理论', '整理 Python 高频面试题（GIL/装饰器/异步/生成器）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 63, 'pm', '实战', '刷 LLM 相关面试题（Token/RAG 原理/Agent/幻觉），每题写要点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 63, 'ev', '复盘', '把难题做成闪卡（Anki）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 63, 'extra', '素材', '口述：RAG 的完整流程，目标 90 秒讲清，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 64, 9, 3, '面试基础：前端 + 系统设计', '前后端通吃');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 64, 'am', '理论', '复习前端高频题（响应式/性能/工程化），结合 AI 应用场景', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 64, 'pm', '实战', '练 2 道 AI 应用系统设计题（如''设计一个 AI 客服''）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 64, 'ev', '复盘', '整理系统设计答题模板', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 64, 'extra', '素材', '对着镜子讲：设计 AI 客服系统，计时 5 分钟', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 65, 9, 3, '模拟面试 1', '实战演练');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 65, 'am', '理论', '复习前 3 天内容，准备被提问', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 65, 'pm', '实战', '找人/用 AI 做一次模拟面试，录音复盘', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 65, 'ev', '复盘', '记录答得不好的点，补练', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 65, 'extra', '素材', '写复盘：哪些表达不清晰，怎么改进（针对性练表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 66, 9, 3, '作品 3 规划（加分项）', '做一个有传播力的 Demo');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 66, 'am', '理论', '头脑风暴：做一个能火的小 Demo（如 AI 表情包/AI 取名）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 66, 'pm', '实战', '选定方向，写最小实现计划', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 66, 'ev', '复盘', '评估传播潜力（有没有分享点）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 66, 'extra', '素材', '口述：我的 Demo 为什么会有人想用，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 67, 9, 3, '周复盘 + 投递准备', '求职物料齐备');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 67, 'am', '理论', '回顾本周，确认简历+讲解+面试题都备好', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 67, 'pm', '实战', '整理目标公司清单（20 家），按优先级排序', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 67, 'ev', '复盘', '写周记：求职心态调整，ISTP 如何应对面试社交', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 67, 'extra', '素材', '对着镜子完整自我介绍 1 分钟，练到自然', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 68, 10, 3, '投递第一批', '投出 10+ 简历');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 68, 'am', '理论', '研究各招聘平台（Boss/拉勾/猎聘）的投递技巧', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 68, 'pm', '实战', '投递第一批 10-15 家，记录每家岗位要求', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 68, 'ev', '复盘', '建立投递追踪表（公司/岗位/状态/反馈）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 68, 'extra', '素材', '口述：我的求职策略是什么，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 69, 10, 3, '作品 3 开发', '快速出 Demo');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 69, 'am', '理论', '规划 Demo 开发，控制在 2 天内出可用版本', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 69, 'pm', '实战', '实现作品 3 核心功能，部署上线', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 69, 'ev', '复盘', '记录快速开发的心得（MVP 思维）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 69, 'extra', '素材', '发动态/小红书：我做了个 AI 小工具（练公开成果展示）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 70, 10, 3, '作品 3 传播', '让 Demo 被看见');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 70, 'am', '理论', '学习技术 Demo 传播技巧（标题/配图/平台）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 70, 'pm', '实战', '把作品 3 发到小红书/掘金/V2EX，附在线体验链接', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 70, 'ev', '复盘', '记录传播数据和反馈', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 70, 'extra', '素材', '口述复盘：我的 Demo 传播效果如何，为什么，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 71, 10, 3, '面试实战 1', '第一场真面');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 71, 'am', '理论', '复习该公司的岗位要求，准备针对性回答', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 71, 'pm', '实战', '参加第一场面试，结束后立即录音记录问题', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 71, 'ev', '复盘', '写面试复盘：答得好/不好的点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 71, 'extra', '素材', '针对答不好的问题，补练表达，录音对比', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 72, 10, 3, '查漏补缺', '补面试暴露的短板');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 72, 'am', '理论', '根据面试复盘，列出待补知识点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 72, 'pm', '实战', '集中补练薄弱环节，更新闪卡', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 72, 'ev', '复盘', '更新简历/讲解稿（根据面试反馈优化）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 72, 'extra', '素材', '对着镜子讲作品，刻意改掉面试中暴露的表达问题', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 73, 10, 3, '持续投递 + 面试', '投递 + 面试并行');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 73, 'am', '理论', '继续投递第二批 15 家，跟进第一批反馈', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 73, 'pm', '实战', '参加能约到的面试，每场后立即复盘', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 73, 'ev', '复盘', '更新投递追踪表', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 73, 'extra', '素材', '口述：我的面试通过率分析，录音（练自我分析表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 74, 10, 3, '周复盘 + 策略调整', '投递面试复盘');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 74, 'am', '理论', '回顾本周投递面试数据，找规律', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 74, 'pm', '实战', '调整投递策略（行业/公司规模/薪资预期）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 74, 'ev', '复盘', '写周记：求职第 2 周，心态和策略调整', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 74, 'extra', '素材', '录 2 分钟：我面试最大的收获是什么（练积极复盘表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 75, 11, 3, '技术博客输出', '公开表达 + 个人品牌');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 75, 'am', '理论', '学习技术博客写作：选题/结构/可读性', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 75, 'pm', '实战', '把阶段一/二的一个技术点写成一篇博客发布', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 75, 'ev', '复盘', '记录博客写作心得', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 75, 'extra', '素材', '发动态：我的第一篇 AI 技术博客（练公开表达里程碑）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 76, 11, 3, '开源贡献（可选）', '参与社区提升背书');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 76, 'am', '理论', '找一个 AI 相关开源项目，读源码，找 good first issue', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 76, 'pm', '实战', '提一个 PR 或写一篇源码解读', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 76, 'ev', '复盘', '记录参与开源的流程', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 76, 'extra', '素材', '口述：为什么参与开源对求职有帮助，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 77, 11, 3, '面试实战 2', '高频面试');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 77, 'am', '理论', '持续投递 + 面试，目标本周 3-5 场', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 77, 'pm', '实战', '每场面试后立即录音复盘', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 77, 'ev', '复盘', '更新面试问题库和应答预案', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 77, 'extra', '素材', '找朋友模拟''压力面''，练被追问时的表达稳定性', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 78, 11, 3, '薪资谈判', '懂行情会谈薪');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 78, 'am', '理论', '研究 AI 岗位薪资行情（看准/Levels/同行打听）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 78, 'pm', '实战', '准备谈薪话术（期望/底线/让步条件）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 78, 'ev', '复盘', '整理谈薪 checklist', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 78, 'extra', '素材', '对着镜子练谈薪对话，录音听语气是否自信', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 79, 11, 3, '作品深度打磨', '让作品更抗问');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 79, 'am', '理论', '根据面试反馈，找出作品被追问最多的点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 79, 'pm', '实战', '针对性优化作品代码和文档', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 79, 'ev', '复盘', '补充性能/安全/扩展性的设计说明', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 79, 'extra', '素材', '口述：如果用户量涨 100 倍我的架构怎么演进，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 80, 11, 3, '周复盘 + Offer 评估', '拿到意向并评估');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 80, 'am', '理论', '回顾本周，盘点在手 Offer/流程中的公司', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 80, 'pm', '实战', '评估 Offer：薪资/团队/方向/成长，做决策矩阵', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 80, 'ev', '复盘', '写周记：求职第 3 周，如何选择', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 80, 'extra', '素材', '录 2 分钟：我怎么评估一个 Offer（练决策表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 81, 11, 3, '表达专项强化', '集中补表达短板');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 81, 'am', '理论', '回顾所有面试录音，归纳表达问题（卡顿/啰嗦/逻辑乱）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 81, 'pm', '实战', '针对性练习：每天对着镜子讲 3 个技术点，录音回听', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 81, 'ev', '复盘', '整理''我的表达改进清单''', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 81, 'extra', '素材', '完整录一遍自我介绍+作品讲解，对比 Day1 的录音看进步', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 82, 12, 3, '终面 + 决策', '拿到并确认最终 Offer');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 82, 'am', '理论', '准备终面（高管面/HR 面）：动机/规划/文化匹配', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 82, 'pm', '实战', '参加终面，复盘', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 82, 'ev', '复盘', '做最终 Offer 选择', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 82, 'extra', '素材', '口述：我为什么选这家公司，录音（练有理有据地表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 83, 12, 3, '入职准备', '技术栈预热');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 83, 'am', '理论', '了解新公司技术栈，对照补课', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 83, 'pm', '实战', '准备入职材料，了解团队和业务', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 83, 'ev', '复盘', '整理入职 30 天学习计划', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 83, 'extra', '素材', '对着镜子讲：入职后我的 30 天计划，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 84, 12, 3, '知识体系沉淀', '把 90 天整理成体系');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 84, 'am', '理论', '回顾 90 天所有笔记，构建知识地图', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 84, 'pm', '实战', '把知识地图整理成一篇''前端转 AI 应用 90 天''总结长文', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 84, 'ev', '复盘', '发布总结长文到掘金/公众号', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 84, 'extra', '素材', '录 3 分钟：我的 90 天转行之路（练长表达，可作为自媒体素材）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 85, 12, 3, '个人品牌收尾', '公开成果汇总');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 85, 'am', '理论', '整理 90 天公开发布的内容（博客/Demo/动态）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 85, 'pm', '实战', '更新个人主页/GitHub README，展示 AI 能力', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 85, 'ev', '复盘', '记录个人品牌资产清单', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 85, 'extra', '素材', '发一条总结动态：90 天我从前端到 AI 应用（练里程碑表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 86, 12, 3, '复盘 + 查漏', '90 天总复盘');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 86, 'am', '理论', '对照 90 天目标逐项检查完成度', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 86, 'pm', '实战', '补练遗漏的关键技能点', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 86, 'ev', '复盘', '写 90 天总复盘：最大收获/踩的坑/给后来者的建议', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 86, 'extra', '素材', '对着镜子完整讲一遍 90 天经历，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 87, 12, 3, '给后来者分享', '输出转行经验');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 87, 'am', '理论', '把 90 天经验整理成一篇''前端转 AI 应用避坑指南''', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 87, 'pm', '实战', '发布到掘金/知乎/小红书', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 87, 'ev', '复盘', '记录传播反馈', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 87, 'extra', '素材', '录一段：给想转行的人的 3 条建议（练价值输出表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 88, 12, 3, '缓冲日', '处理未尽事宜');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 88, 'am', '理论', '处理求职/入职的收尾事宜', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 88, 'pm', '实战', '补完任何遗漏的任务', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 88, 'ev', '复盘', '整理电脑文件和笔记体系', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 88, 'extra', '素材', '口述：我现在的状态和对未来的期待，录音', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 89, 12, 3, '新阶段规划', '下一程方向');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 89, 'am', '理论', '思考入职后的成长路径（技术深度/业务理解/影响力）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 89, 'pm', '实战', '写未来 6 个月学习与发展计划', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 89, 'ev', '复盘', '把自媒体方向与 AI 职业结合规划', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 89, 'extra', '素材', '对着镜子讲：未来半年的我，录音（练愿景表达）', 0);
INSERT INTO plan_days (roadmap_id, day_no, week_no, stage, theme, output) VALUES (2, 90, 12, 3, '90 天毕业', '毕业总结 + 庆祝');
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 90, 'am', '理论', '回顾整个 90 天打卡系统，导出数据存档', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 90, 'pm', '实战', '完成毕业总结：我做到了什么，下一程去哪', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 90, 'ev', '复盘', '发一条毕业动态/朋友圈（练公开 milestone 表达）', 0);
INSERT INTO todos (roadmap_id, day_no, slot, slot_name, content, done) VALUES (2, 90, 'extra', '素材', '录 3 分钟毕业感言：给 90 天前的自己，练有温度地表达', 0);
